### ISSUE TITLE
if enable this plugin, phpstorm internal completion is broken

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#101]
plugin enabled:
![image](https://user-images.githubusercontent.com/16060165/60380250-ecb9e380-9a74-11e9-8a0b-c81f6fa93196.png)

plugin disabled:
![image](https://user-images.githubusercontent.com/16060165/60380226-95b40e80-9a74-11e9-9f25-66313c0a1ea5.png)

**Comment by klesun** [comment]
sorry, my bad, fixing

**Comment by klesun** [comment]
For history, there was a similar issue some time ago: https://github.com/klesun/deep-assoc-completion/issues/52#issuecomment-436357713

**Comment by manaphp** [comment]
method_exists(var));
all this usage is  not work!!!!!!

**Comment by klesun** [comment]
> method_exists(var));
> all this usage is not work!!!!!!

Could you clarify what do you mean, please? Do you mean that `method_exist($var, '')` does not suggest the method names? I may be wrong, but I believe it's the plugin-specific feature, and it does not work for you now because you disabled the plugin...

**Comment by manaphp** [comment]
var position complete nothing maybe reason is the same------------------ 原始邮件 ------------------
发件人: "Artur Klesun"<notifications@github.com>
发送时间: 2019年6月29日(星期六) 晚上8:52
收件人: "klesun/deep-assoc-completion"<deep-assoc-completion@noreply.github.com>;
抄送: "ManaPHP framework"<182452649@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [klesun/deep-assoc-completion] if enable this plugin, phpstorminternal completion is broken (#101)


 
method_exists(var));
 all this usage is not work!!!!!!
  
Could you clarify what do you mean, please? Do you mean that method_exist($var, '') does not suggest the method names? I may be wrong, but I believe it's the plugin-specific feature, and it does not work for you now because you disabled the plugin...
 
&mdash;

**Comment by manaphp** [comment]
my sample code is not good the function name can not complete------------------ 原始邮件 ------------------
发件人: "Artur Klesun"<notifications@github.com>
发送时间: 2019年6月29日(星期六) 晚上8:52
收件人: "klesun/deep-assoc-completion"<deep-assoc-completion@noreply.github.com>;
抄送: "ManaPHP framework"<182452649@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [klesun/deep-assoc-completion] if enable this plugin, phpstorminternal completion is broken (#101)


 
method_exists(var));
 all this usage is not work!!!!!!
  
Could you clarify what do you mean, please? Do you mean that method_exist($var, '') does not suggest the method names? I may be wrong, but I believe it's the plugin-specific feature, and it does not work for you now because you disabled the plugin...
 
&mdash;

**Comment by klesun** [comment]
Here is the testing build that fixes the completion popup not appearing on `DEBUG_BACKTRACE_IGNORE_ARGS` [2019.06.29.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64863)

**Comment by klesun** [comment]
Deployed in [2019.06.30.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64870)
