### ISSUE TITLE
Everything is a string

### ISSUE THREAD

**Issue by friendlyanon** [klesun/deep-assoc-completion#104]
![1](https://i.imgur.com/vh3Wl9G.png)

PhpStorm 2019.2 EAP  
Build #PS-192.5438.24, built on June 27, 2019  
Runtime version: 11.0.3+12-b304.2 amd64  
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
Windows 10 10.0  
GC: G1 Young Generation, G1 Old Generation  
Registry: run.processes.with.pty=TRUE  
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.intellij.ideolog, mobi.hsz.idea.gitignore, BashSupport, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.laravel, de.espend.idea.php.annotation, lv.midiana.misc.phpstorm-plugins.deep-keys, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv

Edit: same happens with PSALM notation and `key => (type)` notation as well

**Comment by klesun** [comment]
Thanks. It shows `string` because it's the type of what will be inserted =-D. Will fix in next release.

**Comment by klesun** [comment]
Argument keys completion will look like this now: (`from usage` will be displayed instead of `string`)
![image](https://user-images.githubusercontent.com/5202330/61584365-e5e33580-ab35-11e9-9410-fdf2d90153ff.png)

Dunno how useful it would be to show actual value types instead of plain `from usage`, if you think it would, I could file a separate low priority feature request as it would take some time to implement...

**Comment by friendlyanon** [comment]
This is better, however what's the point of annotating the parameter properly if the type annotations can't be observed in the autocomplete?  
Very good plugin either way. Keep up the good work!

**Comment by klesun** [comment]
> what's the point of annotating the parameter properly if the type annotations can't be observed in the autocomplete

Supposedly for the main completion popup _inside_ the `group()` function. 
![image](https://user-images.githubusercontent.com/5202330/61613470-ee7c5e80-ac50-11e9-86f4-e5d05b36247d.png)

But good point. I'm just being lazy here. I filed the issue - https://github.com/klesun/deep-assoc-completion/issues/106, one day I'll get to it.

**Comment by klesun** [comment]
`string` -> `from usage` fix released - [2019.07.24.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/66026)

**Comment by klesun** [comment]
`from usage` -> _actual type_ fix released - [2020.04.14.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/83638)
