### ISSUE TITLE
completion space before parentheses

### ISSUE THREAD

**Issue by MartkCz** [klesun/deep-assoc-completion#112]
![image](https://user-images.githubusercontent.com/10145362/64074517-8f2c5800-ccac-11e9-8282-54e2eabc59b4.png)

Expected: `->test()`
but given: `->test ()`

**Comment by klesun** [comment]
Fixed in [2019.09.01.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/68078)
