### ISSUE TITLE
Annotation psalm/phan `@return` support

### ISSUE THREAD

**Issue by MartkCz** [klesun/deep-assoc-completion#113]
![image](https://user-images.githubusercontent.com/10145362/64074577-59d43a00-ccad-11e9-9ca5-d23de7c28af6.png)

**Comment by klesun** [comment]
Seems to not work with non-class functions

**Comment by klesun** [comment]
Fixed in [2019.09.01.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/68069)
