### ISSUE TITLE
Class property autocompletion

### ISSUE THREAD

**Issue by RobinRadic** [klesun/deep-assoc-completion#114]
Hi! 
I think this example explains it all.
```php
class BasePlugin
{
    /**
     * @var array = [$name => ['uses' => '', 'action' => '']]
     */
    public $routes = [];

}

$p = new BasePlugin;
$p->routes['asdfasdf']['action']; // completion works


class MyPlugin extends BasePlugin
{
    public $routes = [
        'a' => [
            // completion does not work
        ]
    ];
}
```

Am i doing something wrong or is this not supported?

**Comment by klesun** [comment]
Hi. There is not such feature yet. I'll add it in the next release.

**Comment by klesun** [comment]
Released the feature in [2019.09.18.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/68956)
![image](https://user-images.githubusercontent.com/5202330/65153702-bd829500-da19-11e9-93ec-a7fbcbc628f3.png)

**Comment by RobinRadic** [comment]
I just got a notice in my editor that `deep-assoc-completion` had a update. I was like "nahh no way!?"

You sir are amazing. Thanks a lot for this fast update!

**Comment by klesun** [comment]
glad to serve =-D
