### ISSUE TITLE
Class method resolving problem?

### ISSUE THREAD

**Issue by daniser** [klesun/deep-assoc-completion#115]
method D() resolved correctly:
![ok](https://user-images.githubusercontent.com/5169543/65755672-dc68e180-e113-11e9-85ce-987ca7450519.png)
But when I do the same from included file, it highlight yellow:
![notok](https://user-images.githubusercontent.com/5169543/65755740-fdc9cd80-e113-11e9-94c5-7a4cc8839281.png)
Anyway I can reach method by clicking on it with Ctrl.

**Comment by klesun** [comment]
You sure _Ctrl + click_ does not work? The yellow highlighting is generated by phpstorm itself, and I sadly [can't remove it](https://github.com/klesun/deep-assoc-completion/issues/34) even though plugin manages to resolve the method just fine. But the _Ctrl + click_ and completion should still work even when method is highlighted. At least it does for me:
![image](https://user-images.githubusercontent.com/5202330/65757866-7fffc500-e107-11e9-9489-df8d919e13fd.png)

**Comment by klesun** [comment]
Oh, lol, sorry misread "I can reach method" as "I can't reach method"

**Comment by klesun** [comment]
The only thing I could possibly do is to just tell IDEA that any time it tries to take a key from array, it's type is `mixed` rather than `null`, then it won't ever highlight a method on an object taken from the array... I guess I'll do that, will take some time.

**Comment by daniser** [comment]
> The only thing I could possibly do is to just tell IDEA that any time it tries to take a key from array, it's type is `mixed` rather than `null`, then it won't ever highlight a method on an object taken from the associative array... I guess I'll do that, will take some time.

Ok, thanks for the answer. I think it will be the optimal solution.

**Comment by klesun** [comment]
Released in [2019.09.30.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/69643)

![image](https://user-images.githubusercontent.com/5202330/65913389-5a044a00-e3bf-11e9-88d6-dd4d5de6901d.png)
