### ISSUE TITLE
Using phpdoc with numeric array for List

### ISSUE THREAD

**Issue by JasonTheAdams** [klesun/deep-assoc-completion#116]
At times I'll do something like this:
```php
function doAndGetSomething() {
  // do things
  return [$classAInstance, $classBInstance];
}

[$classA, $classB] = doAndGetSomething();
```
It's possible there's already a way to do this, but how would I write the docblock for `doAndGetSomething` do indicate the type of what's being returned per index? I tried `@returns array [ClassA, ClassB]` and `@returns array [0 => new ClassA, 1 => new ClassB]`, but autocomplete doesn't seem to kick in.

If I do `doAndGetSomething()[0]` then the autocomplete kicks in properly. Perhaps this just doesn't support the `list` operator?

**Comment by klesun** [comment]
Um, possibly yes, but if you actually write it as `@returns` rather than `@return` I think that would be more likely the reason. I believe [@return](https://docs.phpdoc.org/references/phpdoc/tags/return.html) is the only valid phpdoc tag name.

**Comment by klesun** [comment]
Upd.: never mind my `@returns` comment, I reproduced the issue, it indeed does not work with the php 7.1 `[]` tuple assignment. Will fix.

**Comment by JasonTheAdams** [comment]
Awesome, thanks! The `@returns` thing was just a Github typo. I wasn't copy and pasting.

Good to know it works with the old `list()` syntax.

**Comment by klesun** [comment]
The php 7.1 spport `[]` added in release [2019.10.01.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/69712)

![image](https://user-images.githubusercontent.com/5202330/65999139-78dd0c00-e4a5-11e9-950d-10dbffebcafd.png)

**Comment by JasonTheAdams** [comment]
Just updated, tested, and it works great! Thank you for doing this so quickly!
