### ISSUE TITLE
Traits and @method

### ISSUE THREAD

**Issue by berkayunal** [klesun/deep-assoc-completion#118]
Hi,

Do you have any recommendations for the following case (Traits and @method definition)

```php
<?php

class ProductModel
{
    use HasUserTrait;

    public function testMethod()
    {
    }
}

/**
 * @method XXX byUser($user_id = FALSE)
 */
trait HasUserTrait
{
}

$a = new ProductModel();
$a->byUser("2")->testMethod();

```

Here is a screenshot from the IDE
![IDE_Example](https://user-images.githubusercontent.com/390230/66217156-75c56400-e6cf-11e9-80f1-677c5add1c2e.png)

Any help is appreciated.

Thanks for the plugin! Love it!

**Comment by klesun** [comment]
Does typing `self` in place of `XXX` do what you want?
![image](https://user-images.githubusercontent.com/5202330/66239759-65c77780-e703-11e9-82df-4eac40334a29.png)

**Comment by klesun** [comment]
There is also this plugin-specific completely unjustified here, yet possible format:
![image](https://user-images.githubusercontent.com/5202330/66240128-5c8ada80-e704-11e9-9a73-cdf4d2667396.png)

**Comment by berkayunal** [comment]
Hi

There are some kind of weirdness here. 

1. When used by "self" autocomplete does not show related method.  I wonder why does this behave different in yours than mine

![sc](https://user-images.githubusercontent.com/390230/66242661-b42c4480-e70a-11e9-9245-8eda7fe46fc3.png)

2. When used by "mixed|static" autocomplete shows the method but it does recognize the method as used so you cannot use "find usages" in my ide. test_method() is grayed as show in the second screen shot. Also when i checked your screenshot i have seem the test_method() is not grayed?

![sc2](https://user-images.githubusercontent.com/390230/66242813-213fda00-e70b-11e9-9c5d-060d5dc6f699.png)

![sc2](https://user-images.githubusercontent.com/390230/66243306-ceffb880-e70c-11e9-8d0d-0ed119f14b40.png)

The most important is the "find usage" and "jump to declaration" cause when you try to refactor the code if would not find the usages and definitions.

Thanks for the quick response

**Comment by klesun** [comment]
Just a guess, but could it be that you are trying this in a _New Scratch File_? I noticed that phpstorm seems to ignore classes defined there...

**Comment by klesun** [comment]
Ok I'm closing this issue, as it has nothing to do with the plugin (right?). 
Hope you'll figure out where your problem is. The only more things I can advise are to:
1. Try renaming the classes to anything else (I had some glitches with IDEA when some FQN indexes got broken and renaming them helped)
2. Reset cache: _File ->Invalidate Caches / Restart_
3. Ask authors of this functionality for support: https://intellij-support.jetbrains.com/hc/en-us/?phpstorm
