### ISSUE TITLE
connect two class

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#122]
model::where() return a Query instance, can query method's use the properties of model to completion?

```php
/**
     * @param int|string|array $filters =get_object_vars(new static)
     *
     * @return \ManaPHP\QueryInterface
     */
    public static function where($filters)
```

**Comment by manaphp** [comment]
only model::where can perfect, ...

**Comment by klesun** [comment]
Maybe you could use [psalm](https://github.com/klesun/deep-assoc-completion/issues/77#issuecomment-491637176) `@template` syntax? (like generics in java)
```php
    /**
     * @param int|string|array $filters =get_object_vars(new static)
     *
     * @return \ManaPHP\QueryInterface<City>
     */
    public static function where($filters)
```

**Comment by manaphp** [comment]
all model use same method implementation, can use static instead of XXX usb classs name?

**Comment by manaphp** [comment]
query share the proerties of dynamic model

**Comment by klesun** [comment]
I think I know an elegant way how this could be declared. I'll make a small patch to `QueryInterface.php` (by adding the model class as a `@template` parameter to `QueryInterface` class) and will hear your thoughts on it.

**Comment by manaphp** [comment]
> I think I know an elegant way how this could be declared. I'll make a small patch to `QueryInterface.php` (by adding the model class as a `@template` parameter to `QueryInterface` class) and will hear your thoughts on it.
> (possibly will add some new formats support to the plugin for that to work)


 /**
     * @param int|string|array $filters =get_object_vars(new static)
     *
     * @return \ManaPHP\QueryInterface<`static`>
     */
    public static function where($filters)

is perfect!!!

**Comment by manaphp** [comment]
only A proerties replace of B properies, methods don't need

**Comment by klesun** [comment]
Related to https://github.com/klesun/deep-assoc-completion/issues/77

**Comment by klesun** [comment]
Released in [2019.11.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/72147)

![Uploading image.png…]()

**Comment by manaphp** [comment]
> Released in [2019.11.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/72147)
> 
> ![image](https://user-images.githubusercontent.com/5202330/68726653-d303dd80-05ca-11ea-99bc-9515d99d48d4.png)



very good ,,,but if i write the phpdoc in queryinterface, it can not work.

![QQ图片20191113111226](https://user-images.githubusercontent.com/16060165/68730015-80481700-0606-11ea-989a-db90cdf21b63.png)

**Comment by klesun** [comment]
Did you add the `@template M` and `@param string|array $fields = get_object_vars(new M)` in your `QueryInterface.php` ?

**Comment by manaphp** [comment]
> Did you add the `@template M` and `@param string|array $fields = get_object_vars(new M)` in your `QueryInterface.php` ?

sorry, i make a mistake, written @tempate in query.php...

**Comment by manaphp** [comment]
* @param string $field =get_object_vars(new Model)[$i]

can not work, only complete '0' from usage

**Comment by klesun** [comment]
you probably want something like `@param string $field = array_keys(get_object_vars(new Model))[$i]`

**Comment by manaphp** [comment]
> you probably want something like `@param string $field = array_keys(get_object_vars(new Model))[$i]`

can i use php implemented function?

**Comment by manaphp** [comment]
> you probably want something like `@param string $field = array_keys(get_object_vars(new Model))[$i]`
> 
> P.S. or just `@param string $field = key(get_object_vars(new Model))`

if correct, but also has a '0'

**Comment by klesun** [comment]
> can i use php implemented function?

Yes, you can use your custom functions as well: (given it's a class method)

![image](https://user-images.githubusercontent.com/5202330/68731231-06993480-05d8-11ea-8583-8500d83445da.png)

**Comment by klesun** [comment]
> it corrects, but also has a '0'

I suspect that this `0` comes from the implementation. It it the `get()` function? If so, the `0` completion probably comes from `Query::first()`

**Comment by manaphp** [comment]
> > can i use php implemented function?
> 
> Yes, you can use your custom functions as well: (given it's a class method)
> 
> ![image](https://user-images.githubusercontent.com/5202330/68731231-06993480-05d8-11ea-8583-8500d83445da.png)
> 
> Using non-class functions is currently not possible. If you need that, let me know, I'll add that to my todo list.

method of others class is ok?

if supports non-class function,  can we write it in .phpstorm.meta.php file?

**Comment by manaphp** [comment]
> > it corrects, but also has a '0'
> 
> I suspect that this `0` comes from the implementation. Is it the `get()` function? If so, the `0` completion probably comes from `Query::first()`

yes ,can we ignore all number?

**Comment by klesun** [comment]
> method of others class is ok?

yup

> if supports non-class function, can we write it in .phpstorm.meta.php file?

yes, as long as you refer to it with full name including namespace, like `@param $arg \PHPSTORM_META\doStuff()`

**Comment by manaphp** [comment]
> > method of others class is ok?
> 
> yup
> 
> > if supports non-class function, can we write it in .phpstorm.meta.php file?
> 
> yes, as long as you refer to it with full name including namespace, like `@param $arg \PHPSTORM_META\doStuff()`

any expression?

**Comment by klesun** [comment]
> yes ,can we ignore all number?

I'll look into that, but the preliminary answer is: no, it's complicated, since the idea of the plugin is to suggest _all possible types_, including those that happen only in certain argument signatures

**Comment by klesun** [comment]
> any expression?

yes

**Comment by manaphp** [comment]
> > yes ,can we ignore all number?
> 
> I'll look into that, but the preliminary answer is: no, it's complicated, since the idea of the plugin is to suggest _all possible types_, including those that happen only in certain argument signatures

ok, it is not a  question.
