### ISSUE TITLE
can we complete the path string? (blade template engine)

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#124]
used in template

**Comment by klesun** [comment]
you are on a rampage =-D

**Comment by klesun** [comment]
By template you mean like `.twig` or smarty?

**Comment by manaphp** [comment]
> By template you mean like `.twig` or smarty?

sword: customized blade template engine

**Comment by manaphp** [comment]
> you are on a rampage =-D

i hate input string which can not be completed

**Comment by klesun** [comment]
> sword: customized blade template engine

If you give me some detailed test cases, I guess there won't be problems for me to add the completion (never used neither _sword_, nor _blade_ tbh)

Ideally, a minimal test case with all php/blade files with a comment above the line where completion should happen with the keywords that should be suggested.

**Comment by manaphp** [comment]
> > you are on a rampage =-D
> 
> i hate inputing string which can not be completed

or can we provide a customized dictionary to complete?

**Comment by klesun** [comment]
> sword: customized blade template engine

Could you, please, provide a link to the "sword" engine homepage? Can't google it...

Does it have same formats as [blade](https://laravel.com/docs/5.7/blade)?

**Comment by pbowyer** [comment]
Having this for Twig would be awesome please!

> Ideally, a minimal test case with all php/blade files with a comment above the line where completion should happen with the keywords that should be suggested.

Would you like a sample project with this set up for Twig?

**Comment by klesun** [comment]
@pbowyer, yes please!

**Comment by klesun** [comment]
I'm still having a hard time getting what is ment by the "path string" here, but, @pbowyer could it be that what you are asking it this - https://github.com/klesun/deep-assoc-completion/issues/119 ?

**Comment by manaphp** [comment]
> I'm still having a hard time understanding what is meant by the "path string" here, but, @pbowyer could it be that what you are asking is actually this - #119 ?

"user/login" "user/logout"

**Comment by pbowyer** [comment]
@klesun I saw #119 but it isn't working to autocomplete my Twig templates, so I assumed it isn't working fully.

Thanks for the reminder, it's been a busy weekend. I'll try and get a sample project done this week.

**Comment by klesun** [comment]
@manaphp I'm closing this, as it's still not clear to me from your messages what you are requesting here.

> Ideally, a minimal test case with all php/blade files with a comment above the line where completion should happen with the keywords that should be suggested.

But I'll reopen if you provide the examples and detailed description of the feature request.
