### ISSUE TITLE
Bug: SabrePnr::$parsed completion stopped working

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#13]
Happened after fix 69ce8aef4eab98882522367d0f588f6d1429be49
![screenshot_2017-09-20_03-29-42](https://user-images.githubusercontent.com/5202330/30621481-03e12a9c-9db4-11e7-901a-c14f9513d882.png)

**Comment by klesun-misc** [comment]
Rebased 3ded2a65be6fe9c1b46776c71953428dc05d1c87 - fix is there
