### ISSUE TITLE
Completion from phpdoc `@method` stopped working because phpstorm now supports it

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#134]
Hence the syntax tree structure got changed:
```
Error in provide_psalmMagicDoc #0  Result does not have expected keys: author, unpopularSong
Error in providePropDocComment #3  Result does not have expected keys: status, affected_rows
```
![image](https://user-images.githubusercontent.com/5202330/71791024-182d1480-303c-11ea-98ca-95b58e4dd16d.png)

**Comment by bravoman** [comment]
Ok, so this is the issue and not my database connection or something like that...

I use this type of "hack" everywhere and it seems to be broken (likely because of this issue 😉 )
![image](https://user-images.githubusercontent.com/1729802/72354017-4b7b3d80-36e5-11ea-9711-ce0c413d8cef.png)

Glad to see you picked it up already.

**Comment by klesun** [comment]
yeah, sorry about that, will fix as soon as I get a bit of free time

**Comment by bravoman** [comment]
You saved me lots of time and possible bugs already, I'll manage until then :D

**Comment by bravoman** [comment]
Seems that the following is not working for me anymore as well:

```php
/**
 * Dockblock
 * @return array [ ['bar' => 'foo'] ] 
 */
public function foo() {
     return $this->bar('foo');
}
```

Not sure if it's related.

**Comment by klesun** [comment]
Will post release number soon

**Comment by klesun** [comment]
Fix for the `@method` issue released in [2020.01.15.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/75839)

![image](https://user-images.githubusercontent.com/5202330/72394205-0a634780-373e-11ea-89a8-023b14d7238f.png)

@bravoman, could you, please, give a bit more context to the [`@return array []`](https://github.com/klesun/deep-assoc-completion/issues/134#issuecomment-574236104) use case? Should the completion be provided in the `$this->bar('')` string argument? What is the implementation of the `$this->bar` then?
Did you mean something like this, per chance?
![image](https://user-images.githubusercontent.com/5202330/72394390-ba38b500-373e-11ea-9d87-0a964507668f.png)
Or like this?
![image](https://user-images.githubusercontent.com/5202330/72394413-d76d8380-373e-11ea-9890-61fcd5b2682c.png)

**Comment by bravoman** [comment]
The first one.

**Comment by klesun** [comment]
Does it work now? (the fix supposedly should not have affected the `@return` tag, but still...)

**Comment by klesun** [comment]
If it still does not work, could you, please file a separate issue with minimal reproducible case and you phpstorm version?

**Comment by klesun** [comment]
Btw, as a side note, relating your "hack" for db table completion, you may find [this](https://github.com/klesun/deep-assoc-completion/issues/123#issuecomment-552257721) helpful - you can type `@method array getById(int $id) = Magic::dbRow('my_table')` instead of `@method array getById(int $id) = (new \PDO())->query('SELECT * FROM my_table')->fetch(\PDO::FETCH_ASSOC)`

**Comment by bravoman** [comment]
> Does it work now? (the fix supposedly should not have affected the `@return` tag, but still...)

Works! But it turns out I had an error in my docblock code. Forgot the @ before return 😬 🤦‍♂ 

You can close this issue.



> Btw, as a side note, relating your "hack" for db table completion, you may find [this](https://github.com/klesun/deep-assoc-completion/issues/123#issuecomment-552257721) helpful - you can type `@method array getById(int $id) = Magic::dbRow('my_table')` instead of `@method array getById(int $id) = (new \PDO())->query('SELECT * FROM my_table')->fetch(\PDO::FETCH_ASSOC)`

That's awesome! Seems like something for the Readme.md so everyone can use this 👍
