### ISSUE TITLE
A bug, Refactor: Move Namespace causes infinite loop when plugin is on

### ISSUE THREAD

**Issue by klesun-misc** [klesun/deep-assoc-completion#14]
Moving `Rbs\Process\Terminal` to `Rbs\GdsDirect` freezes IDE fore eternity with this window:

![screenshot_2017-10-17_18-01-44](https://user-images.githubusercontent.com/30558426/31680917-469c0b10-b365-11e7-9b8b-9c073d35a00a.png)

When i disable the plugin, freeze does not happen.

I should reproduce and find the cause. I suspect c8f96bca7e0e62f59b8f47aa1776cc98fb086b54 caused the problem.

Also I think `private int maxExpressions = 20000;` limit could be decreased maybe.

**Comment by klesun** [comment]
Not sure this is related to plugin, but maybe it is: trying to open `public_html` (a folder where lotta different project folders are located) causes idea to hang for more than a minute (didn't wait more - restarted it).

**Comment by klesun** [comment]
This probably is also related to #15

**Comment by klesun** [comment]
I could not reproduce that - my IDEA Ultimate did not hang on that. Though i found that some exceptions were indeed thrown during _Refactor -> Move Namespace_, and c4cc70551f4b7897126c3c8c6219e52aaaf20b1d fixed them. I guess problem is solved.
