### ISSUE TITLE
Magic::dbRow in @return

### ISSUE THREAD

**Issue by amarianski** [klesun/deep-assoc-completion#141]
When I have a method which returns associative array of many rows constructs like this: array [$anyKey=>Magic::dbRow("table")] work perfectly. However when trying: @return Magic::dbRow("table") I get no hints and:
![obraz](https://user-images.githubusercontent.com/12115484/72717953-4bf85600-3b75-11ea-8e74-a776740986aa.png)

**Comment by klesun** [comment]
As a quick workaround, does any of following formats work? 
```
@return array = Magic::dbRow("authorities")
@return = Magic::dbRow("authorities")
@return array Magic::dbRow("authorities")
```

**Comment by klesun** [comment]
I remember there were some issues in writing class name right after the `@return` as phpstorm interpreted it as the return type being this class...

**Comment by amarianski** [comment]
All of them work perfectly :) Great job I really appreciate your plugin! It would be nice if there is a page with documentation of everything possible.

**Comment by klesun** [comment]
https://github.com/klesun/deep-assoc-completion/issues/63
