### ISSUE TITLE
PHPSTORM_META does not work as expected

### ISSUE THREAD

**Issue by mialex** [klesun/deep-assoc-completion#149]
Hi, I'm trying to use **PHPSTORM_META** to be able to set up autocomplete options. I have a pretty huge set of different options, as I have some factory below that, so I want to simplify the list as much as possible by moving some options to the variables.

Here is my class

```
<?php

namespace Test;

class Furniture {

    /**
     * @param array $node
     *
     * @return self
     */
    public function add($node)
    {
        return $this;
    }
}

$class = (new Furniture())
    ->add(['chair' => ['',]])
    ->add(['sofa' => ['']])
    ->add(['window' => ['options']])
    ->add(['table' => ['']]);

```

And this is my meta-file

```
<?php

namespace PHPSTORM_META {

    function describe_data_set() {
        return [
            'options' => [],
        ];
    }

    registerArgumentsSet('optionsSet', [
        'options' => [],
    ]);

    $optionsSet = [
        'options' => [],
    ];

    expectedArguments(\Test\Furniture::add(), 0, [
        'chair' => \PHPSTORM_META\describe_data_set(),
        'sofa' => argumentsSet('optionsSet'),
        'window' => [
            'options' => [],
        ],
        'table' => $data,
    ]);
}
```

The only option which works is the **window**, where sub-values were set up explicitly. For the rest cases, it does not work at all

Environment:
- **deep-assoc-completion**: 2020.02.28.001
- **PhpStorm**: PhpStorm 2020.1 Beta (Build #PS-201.6668.30)

Any ideas on how to solve that?

Thank you!

**Comment by klesun** [comment]
Hi. I'll take a look now.

**Comment by klesun** [comment]
Hm, `chair` seems to work for me too:
![image](https://user-images.githubusercontent.com/5202330/78759194-f0758180-7987-11ea-87ae-b369b942f488.png)


I'll find out why `argumentsSet()` does not work.

**Comment by mialex** [comment]
Thank you for the clarification!

Yes, indeed the issue was due to the duplicate of the function name. I started using meta file when that had to be in the root folder of the project and metafile was a part of the de[endancy, I made a workaround for file content sync. Dut to that I had duplicates for the function.

Thx one more time.

**Comment by klesun** [comment]
Released an update that makes it possible to use function even if it's declared multiple times in the project - [2020.04.14.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/83638)
