### ISSUE TITLE
Array += seems to be treated as =

### ISSUE THREAD

**Issue by tminich** [klesun/deep-assoc-completion#156]
Not sure if this is related to an existing issue, but it looks as if using
```php
$array += [
  'a' => 1
];
```
(in regards to completion help) is treated like
```php
$array = [
  'a' => 1
];
```
instead of the (as far as I know) correct way (```$array = $array+ [];```)
See these screenshots:
![plus_equals_1](https://user-images.githubusercontent.com/51162280/85117332-007ace80-b21f-11ea-9c1e-e2d6b53b0da5.jpg)
![plus_equals_2](https://user-images.githubusercontent.com/51162280/85117346-040e5580-b21f-11ea-94c8-fb6c39bbdf11.jpg)

I use += quite often to set defaults and as you can see EA Extended PHP Inspections is shouting at me for doing it 'wrong' if I use = and + =)

**Comment by klesun** [comment]
Hi. Thanks, good point. Time for one more update =3
(will try to get to it in few hours)

**Comment by klesun** [comment]
Fix released in [2020.06.19.003](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/89438)

![image](https://user-images.githubusercontent.com/5202330/85129621-13e86280-b23c-11ea-93ca-2df64f0bc530.png)

![image](https://user-images.githubusercontent.com/5202330/85129630-1a76da00-b23c-11ea-8f2a-a4cf9057b6ab.png)
