### ISSUE TITLE
Support for new array members

### ISSUE THREAD

**Issue by tminich** [klesun/deep-assoc-completion#157]
Not sure if this is a feature request, bug or consequence of me doing things weird XD

I used psalm/phan syntax to define an array of arrays of a certain format, which, when accessing the top array works fine:
![array1](https://user-images.githubusercontent.com/51162280/85125269-974d8800-b22b-11ea-8c38-d05b4eceea98.jpg)
If I try to add a new member to the array, I do not get any completion:
![array2](https://user-images.githubusercontent.com/51162280/85125313-a7656780-b22b-11ea-83b3-a0665f62daeb.jpg)
Maybe there is a better way to define the array that already works. Since this is just to help me prevent typos inside a function I'm not fixed on a specific declaration syntax, I'd use what works =)

**Comment by klesun** [comment]
Actually, there was almost exact same request by another user: 
https://github.com/klesun/deep-assoc-completion/issues/150

Thanks was bringing this up, almost forgot about it. Conveniently I got a long weekend ahead, hopefully will implement it soon.

**Comment by klesun** [comment]
Released in [2020.06.20.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/89496)

![image](https://user-images.githubusercontent.com/5202330/85204326-65681e80-b31c-11ea-9d53-82699f599c2c.png)

(noticed that for PSALM there is same `from usage` issue as in #155 - filed into a separate issue - #159)
