### ISSUE TITLE
@psalm-property not working correctly

### ISSUE THREAD

**Issue by tminich** [klesun/deep-assoc-completion#160]
I'm having issues with @psalm- versions of @property/@param with not getting completion (or incomplete completion that I'm not sure how it's even generated).
Unfortunately I haven't been able to track down a minimal example for @param/@psalm-param, as soon as I try to simplify it starts to work. There is a simple example for @property/@psalm-property though:

![psalm](https://user-images.githubusercontent.com/51162280/85708863-ee98a000-b6e4-11ea-9e1b-53fca1dbf672.jpg)
 Works in the top case

Note on the @psalm-param case: It might be a case of the @psalm-property not working right somehow breaking completion and 'cross-infecting', but I'm not sure (I've passed a @psalm-property documented property to a function documented with @psalm-param).
I've just tried again after deleteting and undeleting some doc comments and now it works in places where it didn't previously...

Sorry for the somewhat confusing report, but this is a bit tricky to boil down.

**Comment by klesun** [comment]
Thanks, I'll take a look. Very likely that I just do not recognize the `@psalm-property tag. I think I only added support for few of `@psalm-*` tags, will take a look.

**Comment by klesun** [comment]
Yeah, just the `@psalm-param` tag is recognized currently. Hopefully it will be an easy fix now...

**Comment by klesun** [comment]
For reference: https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-specific-tags

**Comment by klesun** [comment]
Fixed in [2020.06.25.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/89893)
![image](https://user-images.githubusercontent.com/5202330/85714106-c617a280-b6f2-11ea-8aef-658aa86e5fb2.png)

**Comment by tminich** [comment]
Thanks, but there is one issue, it stops working if you have both @property and @psalm-property for the same property. The whole point of @psalm-property is to override @property so parsers that understand PSALM syntax use @psalm-property and parsers that don't ignore unfamiliar syntax and 'fall back' to @param.

**Comment by klesun** [comment]
oh,shoot, I had a feeling this typo in my test case will let me know about it again...

**Comment by klesun** [comment]
Fixed for cases when there are both `@property` and `@psalm-property` in [2020.06.26.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/90098)

![image](https://user-images.githubusercontent.com/5202330/85853118-a3e95780-b7ba-11ea-9024-ae81c4315852.png)

(hope nobody gets annoyed by all these updates I spammed last few days...)
