### ISSUE TITLE
Not getting suggestions // argument array keys with `@psalm-param`

### ISSUE THREAD

**Issue by tminich** [klesun/deep-assoc-completion#161]
This is a follow up on the issues I mentioned in issue #160 
I am aware this is a horrible bug report, but essentially I'm at my wits end, so I'm just going to post what I have, maybe with your knowledge of the internals of the plugin you might have an idea.

Basic setting is I'm using Laravel with laravel-ide-helper and need auto-completion defined in comments in a private composer module I wrote. laravel-ide-helper, if you're not familiar with it, inspects Laravel code and generates helper files for IDEs (with some sugar for PHPStorm specifically) to deal with Laravel's quirks and methodology.

### Issue
This is inside a controller where I want suggestions. There are two, but this is very incomplete:
![issue_01](https://user-images.githubusercontent.com/51162280/85845446-8c9f6f80-b7a4-11ea-8254-b11ef4626e24.jpg)

Vehicle::parseTable is defined in a Trait (in vendor) like this:
![issue_02](https://user-images.githubusercontent.com/51162280/85845649-dc7e3680-b7a4-11ea-81f8-aefbbda2d8f3.jpg)

TableParser::parse then goes to a definition generated by ide-helper:
![issue_03](https://user-images.githubusercontent.com/51162280/85845851-3979ec80-b7a5-11ea-9108-53736a721199.jpg)
Which is, in my expectation, where suggestion should be generated from

### A "fix"
If I now go and change that definition and change it like this:
![issue_04](https://user-images.githubusercontent.com/51162280/85846223-cde44f00-b7a5-11ea-826f-1183a0dbf8e0.jpg)

It starts working:
![issue_05](https://user-images.githubusercontent.com/51162280/85846315-e7859680-b7a5-11ea-8d22-b9ebef30ca25.jpg)

The reason I call what I got incomplete is that when I follow it down the rabbit hole even more I have this (TableParserService::parse):
![issue_06](https://user-images.githubusercontent.com/51162280/85847374-8c54a380-b7a7-11ea-8db0-6618f1a3d686.jpg)
so I would expect it to pick up 'lang', 'count' and 'all' as well or nothing.

I'm absolutely ready to test things for you, but from my perspective I have no ideas any more.

**Comment by klesun** [comment]
Seems like either `@psalm-param` is not counted in argument array keys completion like `@param` is. I shall take a look when I have some free time.

**Comment by tminich** [comment]
Actually it looks like it's an issue with PSALM syntax in general and class methods.
```php
class TestD {
    /**
     * @para array $test = ['x'=>'']
     * @param array{x: string} $test
     * @return array
     */
    public function psalm_test2($test): array
    {
        return $test; // Works here
    }
}

$test = new TestD();
$test->psalm_test2(['']); // But not here
```
It works inside the method, but not when the method is called (in contrast to php-style syntax, which works in both cases).

**Comment by klesun** [comment]
Should be fixed now by https://github.com/klesun/deep-assoc-completion/commit/103377f0665367fa276e4b04216c623c73149b31

Release version: [2020.12.11.003](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/versions/stable/105272)

![image](https://user-images.githubusercontent.com/5202330/102714457-4a7c6400-42d7-11eb-8e0f-a2cc10d79408.png)

**Comment by klesun** [comment]
Sorry for such big delay
