### ISSUE TITLE
Can be used for autocomplete string variable.

### ISSUE THREAD

**Issue by andrew-svirin** [klesun/deep-assoc-completion#166]
Your widget helps a lot. Thanks. I have found that widget works very good with arrays.  Does it possible to autocomplete string argument? `public function(string $thisArg)`

**Comment by klesun** [comment]
Hi. Do you mean something like that https://github.com/klesun/deep-assoc-completion/issues/50

**Comment by klesun** [comment]
There is also this PSALM syntax supported
```php
    /** @psalm-param 'aaaa'|'bbbb' $field */
    static function rororor($field)
    {
    }
```
Though it does not seem to work for completion when you _call_ the method... Guess I'll fix that in some of the upcoming releases

**Comment by andrew-svirin** [comment]
Yes. It is great! Can be added some comment for arguments? like on screen?
![image](https://user-images.githubusercontent.com/16819743/93448883-c46a0f00-f8dc-11ea-8697-1ffddc93ed4d.png)

**Comment by andrew-svirin** [comment]
![image](https://user-images.githubusercontent.com/16819743/93449295-3e01fd00-f8dd-11ea-92d4-d4c5692eeb0c.png)
This way autocomplete is working. Anyway i can do like here, if comments for list is not passable.

**Comment by klesun** [comment]
Hm, conceptually, this format is supposed to work as well:
```php
    /**
     * @param $field =
     *     'client-address' ?: // comment 1
     *     'client-data' // comment 2
     */
```
But it does not seem to work. I guess I'll fix that in context of this ticket.

**Comment by klesun** [comment]
Following will be fixed in the next release:
![image](https://user-images.githubusercontent.com/5202330/101985095-7fad0480-3c8e-11eb-895f-c37caa8c291a.png)
![image](https://user-images.githubusercontent.com/5202330/101985111-a10df080-3c8e-11eb-91d9-f8d773cba1dd.png)
