### ISSUE TITLE
Autcomplete in global scope

### ISSUE THREAD

**Issue by andrew-svirin** [klesun/deep-assoc-completion#167]
First of all, thanks for your plugin.

I trying to make autocomplete for Pimple with you plugin, but i do not know how to make autocomplete

For example i have generated file `_ide_helper.php` with such records:
```php
$app['twig.form.renderer']=new Symfony\Bridge\Twig\Form\TwigRenderer();
```

and using in other files like this
```
$app['twig.form.renderer']->render(); //autocompletes good.

function($app){
$app['twig.form.renderer']->render(); //do not autocompletes.
}

function() use ($app){
$app['twig.form.renderer']->render(); //do not autocompletes.
}
```

Question: Is it possible to force autocomplete for some variable be autocompleted global?

**Comment by klesun** [comment]
Hi. I believe you need bind with `global $app;` to use a global variable in a function

**Comment by andrew-svirin** [comment]
```php
$app['twig.form.renderer']=new Symfony\Bridge\Twig\Form\TwigRenderer();
$app['twig.form.renderer']->render(); //here works
function() use ($app){
$app['twig.form.renderer']->render(); //here not works
}
```

**Comment by andrew-svirin** [comment]
With global initialization do not working also (

![image](https://user-images.githubusercontent.com/16819743/94787809-76c0cc80-03db-11eb-8c5e-577441044b98.png)

**Comment by klesun** [comment]
hm... could it be that you are using a "Scratch File" for this code?

**Comment by klesun** [comment]
I had this issue reproducing in a _Scratch File_, but when I created a real `index.php` file, it worked ok

**Comment by klesun** [comment]
![image](https://user-images.githubusercontent.com/5202330/94791256-09636a80-03e0-11eb-9453-89ded9693f48.png)

**Comment by andrew-svirin** [comment]
I understood what the diffference. Your case is working on my code as well.

**Comment by klesun** [comment]
Hm...

![Uploading image.png…]()

**Comment by andrew-svirin** [comment]
Yes, you again right. Then difference in another. I using framework that is very old (Silex) And here `$app` also initialized like `$app = Application();` so i have construction like on screen
![image](https://user-images.githubusercontent.com/16819743/94793808-b68bb200-03e3-11eb-97b4-320c707c478f.png)

**Comment by andrew-svirin** [comment]
![image](https://user-images.githubusercontent.com/16819743/94793932-e2a73300-03e3-11eb-9cd6-91769cf1824c.png)
![image](https://user-images.githubusercontent.com/16819743/94793963-ec309b00-03e3-11eb-9d25-3c2aa82f4281.png)
![image](https://user-images.githubusercontent.com/16819743/94793986-f2bf1280-03e3-11eb-9976-97ce3904414e.png)

**Comment by klesun** [comment]
I wonder what causes plugin to go bananas here...

**Comment by klesun** [comment]
Yeah, I think it's the `use()`. Can you remove `$app` from the `use()` list? You closure on it with `global` anyway, so it should still work...

**Comment by andrew-svirin** [comment]
![image](https://user-images.githubusercontent.com/16819743/94800318-13d83100-03ed-11eb-8c23-6e4a63a58c7a.png)
This way works. Thanks a lot for assist.
