### ISSUE TITLE
Include upcoming usages in the current scope for autocompletion

### ISSUE THREAD

**Issue by pretzlaw** [klesun/deep-assoc-completion#168]
An array is filled to be used in an function:

```php
		$data = $this->createCommentData();
		$data[' ...
		
		wp_update_comment( $data );
```

When adding another field I use autocomplete to get all the possible fields.

![grafik](https://user-images.githubusercontent.com/24290366/98529475-f1ec8c80-227d-11eb-858f-e7d9ee235f95.png)

Unfortunately only the fields that are defined in `$this->createCommentData()` can be seen.
The fields that `wp_update_comment` allows are not shown (e.g. "comment_ID").

But when using the variable in some future context it would be great if the autocomplete shows those accepted fields too.

Notes:

* Having this for the current scope would be nice.
* Checking nested calls would be gold but may take too much runtime.

**Comment by klesun** [comment]
Hi. While not exactly the way you asked, but in current implementation you can achieve same this way:

![image](https://user-images.githubusercontent.com/5202330/98598235-d2d41600-22e2-11eb-8353-0eb29a405e59.png)

**Comment by klesun** [comment]
I want to implement this, but dunno when I'll get the time...

**Comment by klesun** [comment]
Will be available in the next release:
![image](https://user-images.githubusercontent.com/5202330/102724570-2772a400-4319-11eb-9514-5d0b073d18e9.png)

**Comment by klesun** [comment]
I did not implement few features that could go nicely with this:
- Completion of sub-keys: `$arr['key1'][$i]['key2']`
- GoTo definition for such keys
- Instant completion in square brackets without typing quotes.
- Putting caret after the closing bracket upon completion (maybe even automatically add `=` and `;`)

If anyone is positive that some of them are worth implementig, ping me please, I'll spend some more time on this then.
