### ISSUE TITLE
Support 2020.2.3 PHPStorm version

### ISSUE THREAD

**Issue by Deifinger** [klesun/deep-assoc-completion#170]
Could you make support over 2019.2.4+ that you did?

**Comment by klesun** [comment]
Hi. What specifically do you mean? Does plugin not work in 2020.2.3 PHPStorm?

**Comment by Deifinger** [comment]
Exactly. I tried to install it, restarted IDE and it disappeared from the installed plugins list. Tried to do it again and it disappeared again. No errors or warnings in UI

**Comment by klesun** [comment]
I just installed fresh phpstorm 2020.2.3, it seems to work ok

![image](https://user-images.githubusercontent.com/5202330/100248757-89bbcd00-2f44-11eb-80ff-57509df6d955.png)

PhpStorm 2020.2.3
Build #PS-202.7660.42, built on October 16, 2020
Licensed to deep-assoc-completion / Artur Klesun
Subscription is active until March 6, 2021
For non-commercial open source development only.
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: lv.midiana.misc.phpstorm-plugins.deep-keys

**Comment by klesun** [comment]
Hm, interesting. What OS are you using? Could it be that you are running IDE in some custom jre (like java 8 instead of bundled idea jre 11)?

**Comment by Deifinger** [comment]
System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Безіменний
      Boot Mode: Normal
      Computer Name: ***
      User Name: ***
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days 21:05

**Comment by klesun** [comment]
Possibly some nasty error happens during initialization. Logs may show more, _Help -> Show Log in Finder_, search for text with "deep-".

Do you have `deep-js-completion` installed per chance?

**Comment by Deifinger** [comment]
And my Java version: 8 Update 271 (build 1.8.0_271-b09)

**Comment by Deifinger** [comment]
Found nothing... too weird

**Comment by klesun** [comment]
Do you not have same problem if you try to install some other plugin? Like symfony or laravel?

**Comment by Deifinger** [comment]
I have no idea what I did exactly, but it works now :) I reinstalled laravel plugin, deep-assoc-completion and deep-js-completion. One thing, what I guess helped me is disabling deep-assoc-completion plugin right after installing, then restarted IDE and enabled it. If anyone will face with it, try disable/enable strategy
