### ISSUE TITLE
Unable to use <pre>

### ISSUE THREAD

**Issue by mylemans** [klesun/deep-assoc-completion#179]
This works:

` @param array $optionsss = ['a' => '']`

This doesn't:

`@param array $options <pre>= ['a' => '']</pre>`

With pre it looks much cleaner when describing a complex array but when I use it the plugin does not process it.

In addition, the reason I was looking at 'pre' was because there seems to be a length limit on 'per field comment' shown (in my tests this was 103 characters)

![image](https://user-images.githubusercontent.com/749261/111621013-c0656e00-87e7-11eb-8770-3368ae48f482.png)

![image](https://user-images.githubusercontent.com/749261/111620974-b5124280-87e7-11eb-989c-391b76aef1f3.png)

Either improvements/fixes would be sufficient for my needs.

**Comment by mylemans** [comment]
Well apparently someone else created an issue for the length thing exactly when I made this issue.. I'd say for my comment remarks, continue at #178

What are the odds.. ;D

**Comment by klesun** [comment]
Hi.
I'm not sure this `<pre>` thingie can be easily supported. Currently plugin expects such dead simple format:
```
@param array $varName = validPhpExpression()
```
To make the format support html tags, I would have to mess with escaping entities and other inconvenient stuff, and I'm so lazy...

Do you have some plugin that makes html content in phpdoc render nicely or are you using some tool that generates documentation pages from the comments? I don't see any difference when adding `<pre>` in my `2020.3.3` phpstorm...
![image](https://user-images.githubusercontent.com/5202330/111622934-72099c80-87f2-11eb-902e-acd4bca04bc7.png)

**Comment by mylemans** [comment]
Example: 

![image](https://user-images.githubusercontent.com/749261/111623338-8b0e4f80-87ea-11eb-815f-276138fcaa42.png)

My plugins:

![image](https://user-images.githubusercontent.com/749261/111623378-9a8d9880-87ea-11eb-91c5-02c1805ef8b5.png)

This sufficient?

**Comment by klesun** [comment]
Yeah, thanks, did not realize at once that you were adding this `<pre>` for _ctrl+q_ popup.

How about such compromise? =-D
![image](https://user-images.githubusercontent.com/5202330/111624135-f872ae00-87f3-11eb-9f9a-81da9111e6a9.png)

**Comment by klesun** [comment]
Or even:
![image](https://user-images.githubusercontent.com/5202330/111624600-8ea6d400-87f4-11eb-987e-add688331c0c.png)

**Comment by mylemans** [comment]
I'd call that a hacky workaround (2nd option is much cleaner though), but usable for now. I'd rather see a correct solution.

That said, with this workaround, you could say that turning this into a low prio todo is defendable.

**Comment by klesun** [comment]
I'm actually considering closing the issue, as the second option seems better than `@param $var <pre>= [...]</pre>` to me. Either way it's a preference thing, but to support your initially proposed format, I'd have to complicate the codebase and spend a considerable amount of time I'm most likely not going to have following few years, while `// <pre>` already works and it does not have extra leading space in the preview.

**Comment by mylemans** [comment]
I rather have a clean solution in the future, but I'd say, close it for now. While I have your attention, can you do multiline comments? Apparently you can do them for psalm style doc, but I cannot get it to work in the way I shown in my example (ie // on the next line without anything in there)

If you think this could be a bug or missing feature, tell me and I could create another issue.

**Comment by klesun** [comment]
By multiline comments, do you mean this?
![image](https://user-images.githubusercontent.com/5202330/111660874-2fa68680-8817-11eb-852e-e4c83dd27996.png)
(`//` on the right continued on next line)

Filed the issue:
https://github.com/klesun/deep-assoc-completion/issues/180
