### ISSUE TITLE
Psalm array, allow union types?

### ISSUE THREAD

**Issue by RobinRadic** [klesun/deep-assoc-completion#182]
Can this be made possible? `step: array|string`
![image](https://user-images.githubusercontent.com/754732/112396949-6b52bc00-8d01-11eb-87ec-fc1973639175.png)

I couldn't find it in the Psalm spec though

**Comment by klesun** [comment]
Hm, it's not shown in the preview popup (popup shows only the first union type to show up faster), but plugin does understand that `step` is a union:
![image](https://user-images.githubusercontent.com/5202330/112439038-5140ca00-8d51-11eb-8d8c-beff06aafe09.png)

Do you want me to patch plugin to make _all_ union types show in the popup when they come from PSALM?

**Comment by RobinRadic** [comment]
Yeah that'd be great. So it shows like 
![image](https://user-images.githubusercontent.com/754732/112439454-69ace680-8d49-11eb-808e-5894802662bd.png)

**Comment by RobinRadic** [comment]
Yeah that'd be great. So it shows like 
![image](https://user-images.githubusercontent.com/754732/112439454-69ace680-8d49-11eb-808e-5894802662bd.png)

**Comment by klesun** [comment]
Ok. Not sure when I'll get to it, but adding to my todo list.

**Comment by klesun** [comment]
Funny enough, when you _call_ the function union _does_ show up:
![image](https://user-images.githubusercontent.com/5202330/112633326-e4592d00-8e41-11eb-9995-74523efbf328.png)

So it's just a small inconsistency, should be easy to fix.

**Comment by klesun** [comment]
Released in [2021.03.26.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/versions/stable/114997)

![image](https://user-images.githubusercontent.com/5202330/112660087-bd105900-8e5d-11eb-8dbe-f7b39be0203c.png)

**Comment by RobinRadic** [comment]
@klesun awesome as always :kissing_heart:
