### ISSUE TITLE
Support @self reference

### ISSUE THREAD

**Issue by 6562680** [klesun/deep-assoc-completion#190]
First i tried to do
```
/** @return array [ 'id' => 123, 'children' => [ ? ] ] */
```
and it is impossible. I just dont know how to mark deep-assoc to know i want to recursive autocomplete in child

Rarely case but needed for me.

How do you think?

**Comment by klesun** [comment]
Hi.
The proper way would probably be by using PSALM typedefs, but this is not supported yet: https://github.com/klesun/deep-assoc-completion/issues/158

One workaround you could use is to define type with a circular function:
![image](https://user-images.githubusercontent.com/5202330/129298523-f1af6efb-a1e2-4679-929a-6aea2dc1d007.png)

```php
function describeNode() {
    return [
        'id' => 123,
        'children' => [describeNode()],
    ];
}

/** @return array = describeNode() */
function doStuff() {

}

doStuff()['children'][0][]
```

**Comment by klesun** [comment]
Let me know if you have more questions regarding the status of annotating circular type structures
