### ISSUE TITLE
Completion for params in factory with extends

### ISSUE THREAD

**Issue by leiha** [klesun/deep-assoc-completion#204]
Hi first ty for the work  :pray: 

I try to have a completion in factory extended 
i tried many things but apparently nothing work :(

```
/**
 * @template T
 */
class SubFactory extends Factory {

    /**
     * @var array<T,bool>
     */
    protected array $ressources = [
        'index'  => true ,
    ];

    /**
     * @param T $name
     */
    public function allow( string $name ) : self {
        return parent::allow( $name );
    }   
}
```

There is a way to accomplish completion for param $name in allow method ?

**Comment by klesun** [comment]
Hi. Do you want the completion to be inferred from the `$ressources` field assigned value?

Afaik, PSALM type annotations don't provide type inference from value, not in the plugin at least.

What you could do, though, is to express the argument accepted string values through `@param $name = array_keys($this->ressources)[$any]`:
```php
class SubFactory extends Factory {

    protected array $ressources = [
        'index'  => true ,
    ];

    /**
     * @param $name = array_keys($this->ressources)[$any]
     */
    public function allow( string $name ) : self {
        return parent::allow( $name );
    }
}


$subFactory = new SubFactory();
$subFactory->allow('');
```
![image](https://user-images.githubusercontent.com/5202330/169155288-6eb21443-7bd4-4227-bcbe-6616c2c58189.png)

**Comment by klesun** [comment]
You may find this document useful:

https://github.com/klesun/deep-assoc-completion/issues/63

**Comment by leiha** [comment]
I had not understood how to work for my case despite the doc :(

**Comment by leiha** [comment]
@klesun :pray: 
I had not understood how to work for my case despite the doc :(
all examples had seemed for me "static" not really dynamic but maybe i'm blind  ^^
it's works as you show me , perfect :)

**Comment by leiha** [comment]
@klesun
i hope i'm not going to abuse :crossed_fingers: 
But can you also explain to me to have the right return type of the method ?


```php
class SubFactory extends Factory {

    protected array $ressources = [
        'index'   => [ 'key1' => '' , 'key2' => ''   ] ,  
        'update' => Action\Update::class,            
    ];

    /**
     * @param $name = array_keys($this->ressources)[$any]
     * @return ??
     */
    public function allow( string $name ) : self {
        return parent::allow( $name );
    }
}


$subFactory = new SubFactory();
$subFactory->allow('');

```

**Comment by klesun** [comment]
Does it not work as is already?
![image](https://user-images.githubusercontent.com/5202330/169162276-f09b3827-4f5f-4cde-8de7-f455d547e6ce.png)

**Comment by klesun** [comment]
The `: self` seems to be sufficient for plugin to understand that return value is the class

**Comment by leiha** [comment]
sorry

**Comment by klesun** [comment]
np

**Comment by klesun** [comment]
If you'll happen to want to use custom expressions in the return type, the syntax is following:
```
@return = array_values($this->ressources)[$any]
```

![image](https://user-images.githubusercontent.com/5202330/169162959-2262a26f-1652-4010-87a1-da8074310d01.png)
