### ISSUE TITLE
Cannot view plugin preferences/settings.

### ISSUE THREAD

**Issue by jpmc** [klesun/deep-assoc-completion#208]
Upgraded to PHPStorm 2022.2 before I stumbled upon this plugin, so perhaps that is a reason. On an M1 Mac.

I was trying to access the settings for the plugin and came across an empty pane instead that said "Select configuration element in the tree to edit its settings."

![image](https://user-images.githubusercontent.com/16089593/182681140-7aa62326-0f1a-43e8-8f82-fcca7bd1a4d5.png)

This does not occur with any other plugins and adjacent menu items when clicked on load their settings fine, and then clicking on deep-assoc-completion makes that pane empty again.

Anyone ideas on what caused this? Perhaps it's a RTFM-type issue where I am not using PHPStorm correctly, but haven't had this issue with other settings/plugins before so I figured I'd file a bug in case.

**Comment by klesun** [comment]
Oh, damn, thanks, looks like I was missing UI Designer dependency during the last build.

Fixed in [2022.08.03.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/versions/stable/204213) release

**Comment by jpmc** [comment]
Just installed the update and it works now!

Holy smoof that was fast, I saw it was closed so quickly I thought it was gonna be a "won't fix"! 😅

Thanks a ton, I really appreciate it!
