### ISSUE TITLE
Not an issue, just a thank you :)

### ISSUE THREAD

**Issue by DanielAGW** [klesun/deep-assoc-completion#214]
Hi @klesun , I just really wanted to thank you so much for this plugin. It has probably saved me hundreds of hours and so much frustration. The autocompletion has been working flawlessly for years and I can't imagine working without this plugin. It's just amazing how well it works even under complex circumstances. Fantastic work, thank you so much!

**Comment by klesun** [comment]
Glad it still works ^_^
I know there were some breaking changes in new versions of phpstorm since last update, too bad I don't have as much time/will nowadays as I used to to properly maintain it ;c
