### ISSUE TITLE
Inconsistent use of type text in completion popup

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#26]
I just noticed the following:

![image](https://user-images.githubusercontent.com/4896363/34667977-a416ba78-f46b-11e7-8be8-e71150a14062.png)

For `bla` you display a static string value instead of its type. (For numbers it gets quoted which is also a small bug).

I suggest to **always show the type at the right column**. So it would be `string` in this case.

If you want to show some static values you can use the "tail text" on your `LookupElementPresention`.
A good example for this implementation are constants in built-in PhpStorm completions:
![image](https://user-images.githubusercontent.com/4896363/34668110-2eaf4c36-f46c-11e7-958f-4dba0dee7801.png)

So in my case the completion for `$options['KEY']` would be:

```
bla = 'xyz'         string
```

` = 'xyz'` is the tail text. I recommend using the "grayed" flag to make this consistent with the mentioned "const" completion. (Notice: there should be a space character before the `=`)

see https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/codeInsight/lookup/LookupElementPresentation.java#L70

**Comment by klesun** [comment]
Thanks, sounds like a good idea. I'll implement this soon. 
It will be a bit tricky with arrays, though, since I show them with keys in some specific format to save space: `{follow_redirects:, bla:}`. But I'll try to make them look consistent too.

**Comment by klesun** [comment]
c1e796c145bc5aeea79c7ddb013b821e99485207
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/42097

![image](https://user-images.githubusercontent.com/5202330/34745771-81b93fea-f589-11e7-9560-0c3906ec2656.png)
