### ISSUE TITLE
Plugin renames "Declaration" action to "viva Denis!"

### ISSUE THREAD

**Issue by hailwood** [klesun/deep-assoc-completion#35]
https://github.com/klesun/deep-assoc-completion/blob/40911e6adbf494ecf60739df3c483b2aa306d6fb/src/org/klesun/deep_assoc_completion/completion_providers/EqStrValsPvdr.java#L115-L120

Mind removing this method please? You now know what it does ;)
![image 1](https://user-images.githubusercontent.com/709773/39842207-b90c2a7a-5439-11e8-9e21-bc617c1e5e06.png)

**Comment by klesun** [comment]
Lol, sorry, my bad.

**Comment by klesun** [comment]
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/45779
