### ISSUE TITLE
Completion for objects

### ISSUE THREAD

**Issue by ms502040** [klesun/deep-assoc-completion#37]
Hi,
Is possible make something like that for completion objects? For example:
~~~~~php
/**
*  @var stdClass $row {
*       @property int id some description
*       @property string name some description
*}
**/
while ($row = $result->fetch_object()) {
  $row->   (suggest - id | name)

~~~~~

**Comment by klesun** [comment]
Yes, sure.
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/46276

![image](https://user-images.githubusercontent.com/5202330/40632451-f755d96a-62ef-11e8-8df0-f7d88f04e212.png)

**Comment by klesun** [comment]
I'd like to note that it is now possible to specify object properties like this as well:
![image](https://user-images.githubusercontent.com/5202330/48558230-bada7f00-e8e0-11e8-9b10-36074415b189.png)

Since casting to object transforms array keys to `\stdClass` properties. This way you can specify indexed arrays in the structure.

**Comment by ms502040** [comment]
Hi,
you doing awesome work, thanks.    
what about class magic method? :wink: 
~~~~php
/**
   * @var $data = (object)['database' =>
   *                    (object)[
   *                    'server' => '',
   *                    'user' => '',
   *                    'pass' => '',
   *                    'database' => '',
   *                    'port' => '5719',
   *                    'socket' => '',
   *                    ],
   *            'max_occurences' => 10,
   *  ]
*/
  private static $data;
  /**
   * @return mixed
   */
  public function getData()
  {
    return self::$data;
  }

  /**
   * @param $key
   *
   * @return self::$data
   * @throws \Exception
   */
  public function __get($key)
  {
    if (isset(self::$data->$key)) {
      return self::$data->$key;
    }
    throw new \RuntimeException('Configuration property '. $key . ' not exists.', 2);
  }
~~~~

`$object->getData->` working good  :smile: 
would be nice if  `$object->` give result as with `getData` method

**Comment by klesun** [comment]
I guess I can add the completion from magic method.
I filed a new issue for this feature: https://github.com/klesun/deep-assoc-completion/issues/56
