### ISSUE TITLE
Problem with inheritance when subclass overrides array

### ISSUE THREAD

**Issue by szkuwa** [klesun/deep-assoc-completion#42]
I have a problem with completion when a subclass overrides parent static property, in my app it's from a trait in parent class but the bug is there even in the simplified version:

![deep-assoc-1](https://user-images.githubusercontent.com/6832734/43456183-c5339c24-94c2-11e8-85f3-a2f9f201463e.jpg)
As seen in the picture it gives completion from the parent class instead of the one from child class.

A way to get around this is to redefine `getArray()` function in the subclass:
![deep-assoc-1b](https://user-images.githubusercontent.com/6832734/43456414-b4f141b2-94c3-11e8-886a-c49572b06402.png)
But it's a lot of unnecessary code

I've tried to type hint array on the parent class like this:
![deep-assoc-2](https://user-images.githubusercontent.com/6832734/43456491-f7d0a9d2-94c3-11e8-8a4e-951dd3466f14.jpg)
But got weird merged result.

Type hinting like
`@return array = static::$array`
or
`@return array = self::$array`
shows completions as in the first pic (`'parentKey'` only)

**Comment by klesun** [comment]
Hi. Thanks for you report, Here is the fix:
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/48357
https://github.com/klesun/deep-assoc-completion/commit/9fd3b79e28fa6dc90ae1658d99a360e2683d4fec
