### ISSUE TITLE
Slow completion

### ISSUE THREAD

**Issue by bazzik** [klesun/deep-assoc-completion#43]
```
PhpStorm 2018.2.1
Build #PS-182.3911.43, built on August 8, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

Laravel 5.6 project.

`$user` is a standard Laravel Model, simple class: 11 simple methods (1-3 lines each), overriding 6 properties, has 2 constants, 14 virtual properties (via `@property` PHPDoc) and 2 `@mixin` to have Laravel's `*\Builder` methods... -- nothing special.

I have not coded actively in this project for a while (few small edit here and there) ... but with latest deep-assoc-completion plugin (**v2018.08.05.001**) completion for ordinary stuff becomes MUCH slower and sometimes I do see entries that definitely come from this plugin heuristics (special icon).

![image](https://user-images.githubusercontent.com/1482298/43954886-0ff946a2-9c96-11e8-9b4a-d3affff2aa57.png)

Screenshot shows around 2 sec delay text. In reality it feels like 3 (up to 4) seconds. The same completion with plugin disabled is instantaneous.

Interesting part is: in most places it's slow like that ... but in some places it's much faster. And I have no idea why. In Controller (on screenshot) it's slow. In service class (plain class that performs operations on user) in one method it's fast, in another -- slow again; variable name does not make the difference...

![image](https://user-images.githubusercontent.com/1482298/43954928-2a6b6754-9c96-11e8-801f-3a81c119bab4.png)

**Comment by bazzik** [comment]
Hi Artur,

Just got plugin auto updated to version **2018.08.16.001**.

That place that I have reported (and 2 others where it showed similar behaviour) is now fast as it would be without this plugin enabled. PhpStorm 2018.2.2 EAP build.

So right now it looks fixed to me (at very least on my code where I've tested it; not extensive testing though).

Many thanks for a quick fix. Much appreciated.

**Comment by klesun** [comment]
Glad it helped somehow. It was really just a quickfix that only disabled plugin in property/method completion if there already are some suggestions. There are still some performance issues in Laravel projects I'll fix soon.

**Comment by klesun** [comment]
Well... my "soon" took longer than I hoped, but the issue should be gone by now.
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/53346

I made various optimizations over past months, most important one was that now each completion option is suggested the moment it is found (in past you had to wait till _all_ options are resolved before popup appears).
