### ISSUE TITLE
Adds invalid completion suggestions

### ISSUE THREAD

**Issue by simPod** [klesun/deep-assoc-completion#46]
When using latest version in IDEA, it adds those completion when selecting PHP class

![image](https://user-images.githubusercontent.com/327717/44617131-caa47300-a85d-11e8-878f-ca49886c554d.png)

Those should not be there

**Comment by klesun** [comment]
Um, what exactly is incorrect? Could you provide more context, like screenshot of code that causes this completion? Is this `@return` php doc completion?

I can remove duplicate suggestions and put my plugin options to the bottom. I can also add an option in config to disable class completion in `@return` tag. Will this satisfy you?

**Comment by simPod** [comment]
Yes, this is `@return` php doc completion, sorry. 

I don't really fancy deep assoc suggestions being before IDE's suggestions. Those suggestions are also a bit incorrect or irelevant as I'm looking for actual class to be imported and not for static access `::` to something on that class.

> I can also add an option in config to disable class completion in @return tag

That would certainly help!

**Comment by klesun** [comment]
Thanks, you were right, it was wrong behavior. Plugin won't suggest class name completion on place of  `@return` type anymore.

https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/49272
