### ISSUE TITLE
php bug report

### ISSUE THREAD

**Issue by dogzy123** [klesun/deep-assoc-completion#48]
java.lang.StackOverflowError
	at org.klesun.deep_assoc_completion.TiEsheMozheshUspetjNaAvtobus
	at org.klesun.lang.DenisBudetVCiv5
	at org.klesun.deep_assoc_completion.EmuTutSkuchno
	at org.klesun.deep_assoc_completion.PriezhaiteKollega
	at org.klesun.lang.Opt.uni(Opt.java:137)
	at org.klesun.deep_assoc_completion.helpers.FuncCtx.hashCode(FuncCtx.java:215)

**Comment by klesun** [comment]
Там внатуре экскепшн падает в `FuncCtx::hashCode()`?

**Comment by dogzy123** [comment]
> Там внатуре экскепшн падает в `FuncCtx::hashCode()`?

at org.klesun.deep_assoc_completion.TiEsheMozheshUspetjNaAvtobus
at org.klesun.lang.DenisBudetVCiv5
at org.klesun.deep_assoc_completion.EmuTutSkuchno
at org.klesun.deep_assoc_completion.PriezhaiteKollega

**Comment by klesun** [comment]
Sorry, I can't find the `TiEsheMozheshUspetjNaAvtobus.java`, can't reproduce.

(приехал на велике, я в соседней комнате)
