### ISSUE TITLE
Use default parameter declaration

### ISSUE THREAD

**Issue by crayssnlabs** [klesun/deep-assoc-completion#53]
Hello there,

it will be very helpful the default parameter will used as documentation to autocomplete inside the function and when it will called.

![default](https://user-images.githubusercontent.com/35770897/47703121-7cc23780-dc1f-11e8-9f1d-359e0d6299ce.PNG)

![default_2](https://user-images.githubusercontent.com/35770897/47703128-83e94580-dc1f-11e8-8936-b08e6b47e924.PNG)

You know what i mean?

**Comment by klesun** [comment]
Done - https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/51591
![image](https://user-images.githubusercontent.com/5202330/47754730-8cd02a80-dca4-11e8-9596-9396e4de9a83.png)
![image](https://user-images.githubusercontent.com/5202330/47754809-c5700400-dca4-11e8-8161-3d3b16a60618.png)

**Comment by crayssnlabs** [comment]
Perfect! It works as expected.
