### ISSUE TITLE
PhpDoc return type

### ISSUE THREAD

**Issue by zored** [klesun/deep-assoc-completion#55]
Hi! Thank you for this great plugin. ❤️ 

It would be great to specify `@return` [same as `@param`](http://midiana.lv/entry/phpstorm-deep-keys/#completionfromphpdoc):
```
@return array = ['a' => 'b']
```

There was also PSR-5 that suggested `ArrayObject<int, string>`, but now I [don't see traces](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#arrays) of this specification.

**Comment by klesun** [comment]
Hi. It is already possible to specify `@return` keys like this:
```php
/** @return array ['a' => 'b'] */
```
![image](https://user-images.githubusercontent.com/5202330/48837795-3c695b80-ed7e-11e8-94bd-0afc6e690713.png)

But I'll add the `=` format too nevertheless.

I can't find traces of `ArrayObject<...>` specification neither.

**Comment by klesun** [comment]
Added support for `@return aray = [...]` format as well. 
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion
![image](https://user-images.githubusercontent.com/5202330/48871911-598a4280-edef-11e8-9064-974950d24507.png)

**Comment by zored** [comment]
Wow, thank you! 😄
