### ISSUE TITLE
Load phpdoc array from a file

### ISSUE THREAD

**Issue by OndrejVasicek** [klesun/deep-assoc-completion#57]
Hi klesun and thank you for your great plugin.
I'd like to ask - is it possible to have array definition in a file? I'm trying something like this in my phpdoc, but it doesn't work.

```
/**
 * @property array[][]  $params = require __DIR__ . '../config/params.php'
 */
```
Array configurations in file are quite common. It seems strange to me to create a Class only to return this configuration array.

**Comment by klesun** [comment]
Hi.
Does `params.php` content looks something like this? (with `return` in global scope)
```php
<?php
return [
    'value1' => 123,
    'value2' => 123,
    'value3' => 123,
];
```
If it does, sure, I'll add that... well even if it does not I guess I will.
http://php.net/manual/en/function.return.php
> If called from the global scope, then execution of the current script file is ended. If the current script file was included or required, then control is passed back to the calling file. Furthermore, if the current script file was included, then the value given to return will be returned as the value of the include call

Though if your `params.php` does not have a global `return`, but just defines global variables, it will require some thinking on the right way to pass this data to plugin...

**Comment by OndrejVasicek** [comment]
Yes, exactly like this. With the return. So do I understand that this function is not implemented yet?
Do you have any idea where it could be finished?

**Comment by klesun** [comment]
Yeah, completion from a script `return` is currently not implemented. Will be done in a an hour I guess.

**Comment by OndrejVasicek** [comment]
Jesus ... this is beyond any expectations. Thank you a lot klesun. I'll wait for it and will use it in my project right away.

**Comment by klesun** [comment]
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/53040

![image](https://user-images.githubusercontent.com/5202330/49762308-4b7a6400-fcc1-11e8-92f5-b8ba4431c78b.png)
