### ISSUE TITLE
Cornercase examples

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#6]
### Here are listed code examples where completion does not work even though it should.

**Comment by klesun** [comment]
`FareQuoteSuperBbActionOutputAdapter.php`
a nice collection of cornercases - look around, you'll find a lot of keys plugin fails to provide completion for.

**Comment by klesun** [comment]
`addFullDateToSabreSegment()` for some reason i don't original segment keys, even though 1d4eaad799f2e85bcf4a23141f08834258c0e0e6 (i believe) is on...

**Comment by klesun** [comment]
`AmadeusBaggageAdapter::joinLocations()`, suspicious, flight segment type info is presetn in `$location` disappears in `$segments`

**Comment by klesun** [comment]
```php
/**
 * wrap private method in a closure to
 * allow passing it outside of this class
 */
private static function closed(callable $meth)
{
    // this could be moved to a helper class - will
    // need to use reflection to call private method
    return function(...$args) use ($meth) {return $meth(...$args);};
}
```
If i call `$meth`, i get the completion, but if i wrap it in `closed`, i don't get it. Probably `use` is not handled correctly.

**Comment by klesun** [comment]
```php
AmadeusPnrFieldsOnDemand::getAllFareRuleRecords()
...
$numToSeg['0']['']; // completion causes lags
$numToSeg[ArrayUtil::getFirst($fare['segmentNumbers'])]['']; // no completion
```

**Comment by klesun** [comment]
`elseif` branches don't get completion from each others. This is correct, but not when they are in a loop:
```php
foreach ($locations as $location) {
    if ($location['type'] === 'flight') {
        $segments[++$i] = $location;
    } elseif ($location['type'] === 'ARNK') {
        $segments[$i][''];
    }
}
```
`$segments[$i]['']` should provide completion from `$location` keys

**Comment by klesun** [comment]
```php
$staySegNums = array_column($this->itinerary->getKeyDestinations($this->geography), 'segmentNumber');
$fares = $this->pricing->collectFcFares($this->itinerary)['fares'] ?? [];
$fareSegNums = Fp::map([ArrayUtil::class, 'getLast'], array_column($fares, ''));
```
Something makes completion in the `array_column` here very long (~10 seconds), i suspect circular references.

**Comment by klesun** [comment]
`$this->data['key'] = $this->data['key']`
this will cause infinite recursion - should do something about that

**Comment by klesun-misc** [comment]
`CheckItineraryPricesAction::execute()` trying to Go To `'pricingList'` results in "Cannot find declaration". I guess it is because of a bug in logic with `elseif`-s

**Comment by klesun** [comment]
### Resolved

**Comment by klesun** [comment]
`PtcPricing.php` - `$this->data['']` does not provide completion, even though it navigates correctly on ctrl+b

**Comment by klesun** [comment]
https://github.com/klesun/deep-assoc-completion/issues/18
