### ISSUE TITLE
Doesn't autocomplete objects

### ISSUE THREAD

**Issue by Agent-J** [klesun/deep-assoc-completion#60]
Great plugin, 
but unfortunately v2018.12.23.001 doesn't autocomplete objects.
PhpStorm v2018.3.2 Build #PS-183.4886.46 (the same was with v2018.1)

![alt text](https://i.imgur.com/juHHYOp.png)

Example:
```php
<?php 

class someSubclass
{
    public $x = 'rrr';
}

class someClass
{
    public function method()
    {
        /**
         * @var $row = (object) [
         *         'subName'       => new \someSubclass,
         *         'childPurchase' => (object) [
         *             'id'    => 'string',
         *             'price' => 12.56
         *         ],
         * ];
         */
        while($row = $result->fetch_object())
        {
            $row->;  // should suggest: subName, childPurchase 
        }
    }
}
```
The same with other notatin:
```php
<?php 

class someSubclass
{
    public $x = 'rrr';
}

class someClass
{
    public function method()
    {
        /**
         *  @var stdClass $row {
         *       @property \someSubclass subName description
         *       @property stdClass childPurchase {
         *           @property int id some description
         *           @property float price
         *       }
         *}
         */
        while($row = $result->fetch_object())
        {
            $row->subName->;        // should suggest: x
            $row->childPurchase->;  // should suggest: id, price 
        }
    }
}
```

Related to issue #37

**Comment by klesun** [comment]
Oh, thanks, I'll take a look now.

**Comment by klesun** [comment]
khem, you are using `@var` instead of `@param` =-D

**Comment by klesun** [comment]
oh, in parent issue reporter also used `@var`... in any case, completion expects `@param` doc tag name for an argument. 

I'll take a look if `@var` is a valid tag name. If it is, I'll add support for it as well.

**Comment by klesun** [comment]
sorry, nevermind my deleted commetns

**Comment by klesun** [comment]
Was broken after 0b97b6a6e40818fa157ce4dbcf6ade0c59a5d283
Fixed in [2018.12.26.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/53569)
![image](https://user-images.githubusercontent.com/5202330/50453463-5da70400-0949-11e9-8240-44a0ca97cd19.png)

**Comment by Agent-J** [comment]
Wow! Impressive support and bugfix speed!
Thanks a lot

However v2018.12.26.001 still lacks nested classes support with alternative notation

![default](https://user-images.githubusercontent.com/941804/50453959-89c88200-0955-11e9-82bc-66c86a8877a7.png)

**Comment by Agent-J** [comment]
In fact I do not use alternate notation, but decided to point out, maybe someone needs =)
Thanks for support
