### ISSUE TITLE
The phpdoc array keys format supported by the plugin.

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#63]
The [README](https://github.com/klesun/deep-assoc-completion/blob/master/README.md) briefly mentions an ability to specify array keys in a doc. I'll describe it a bit more detailed here...

So, basically, in the `@param`, `@var`, `@property`, `@method` and `@return` phpdoc tags, after the variable name, you can type an `=` followed by any valid php expression - it will be parsed by the plugin and used in completion on further references to this variable. 

Example: (specify that var contains the value returned by a function)
```php
/**
 * @param $sale = self::createSale() // a sale confirmed by bookeeping
 */
public function processSale($sale) {}
```
![image](https://user-images.githubusercontent.com/5202330/51793275-b4f0fc00-21b5-11e9-84c8-a841d299597d.png)

__________________________
Another example: (specify associative array keys)
```php
/** @var array $clientData = [
 *     'id' => 1234, // unique id in DB
 *     'activityDt' => new DateTime,
 *     'sales' => [SaleApp::createSale()], // array of one or more sales client had with us over the years
 *     'agentReviews' => [
 *          ['agent' => 'Steeve', 'rating' => 9.5, 'comment' => 'Does his job well'],
 *          ['agent' => 'Tiffany', 'rating' => 6.3, 'comment' => 'Could try harder'],
 *     ],
 *     'soapData' => (object)[ // the data we got from external system
 *         'LoanPast' => 'GOOD',
 *         'Job' => 'WEB DESIGNER',
 *     ],
 * ] */
$clientData = json_decode($text, true);
```
![image](https://user-images.githubusercontent.com/5202330/51793358-1e253f00-21b7-11e9-8d6c-387fdca2fc9c.png)

___________________________
Another example: (specify return type keys)
```php
/** @return array [
 *     'address' => 'Novokuzneckaya Oblastj, Dom 427, Moscow, Russia',
 *     'family' => 'single',
 *     'name' => 'Vasya Pupkin',
 * ] */
private function getExternalData() {}
```
![image](https://user-images.githubusercontent.com/5202330/51793484-19618a80-21b9-11e9-9f26-4da40da8bf06.png)
(an `=` between `@return` and the expression is allowed, but not required)

If there are any questions concerning the format, I guess you are welcome to ask them here.

**Comment by klesun-misc** [comment]
test

**Comment by bravoman** [comment]
Very nice feature!

Does this also allow for specification of a ('virtual') `@method` phpdoc tag it's return value? If so, what would be the syntax for this?

**Comment by bravoman** [comment]
Also I'm curious... If I could add non-static PHP code like this, would that in turn also be type inferred? 

Or would that just be asking for too much? 😉

**Comment by klesun** [comment]
Hi.
`@method` is currently not supported. I can add it, though, I guess it won't be hard.
I guess some Scala-ish syntax like that will look good:
```php
/** 
 * @method array getData() = [
 *     'name' => 'John',
 *     'age' => 27,
 *     'children' => ['Tiffany', 'Bob', 'Marta'],
 * ]
 */
```
I'll write back when this is done (in few days maybe).

______________________________________

By non-static code you mean something like this?
```php
$product = ['name' => 'insurance', 'quantity' => 3, 'price' => '80.00'];
/** @var $sale = ['sellingPrice' => '300.00', 'product' => $product] */
$sale = $this->sellProduct($product);
```
If so, there is no such feature yet either. Though I guess it could be added as well, if this is what you meant...

**Comment by klesun** [comment]
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/58898 - added support for `@method` doc return type.
![image](https://user-images.githubusercontent.com/5202330/53595467-44167880-3b95-11e9-8d4d-8125e406c0cf.png)

@bravoman, please, confirm that I understood you correctly about the _non-static php code_ before I start implementing it.

**Comment by bravoman** [comment]
Sweet! Yes, that is what I meant! 

With regards to the non-static code I meant something like this:

```php
/**
 * @method getById(int $id) = [
 *     'id' => 1,
 *     'username' => 'user_name'
 * ]
 * @method getAll() = [
 *     0 => self::getById(1)
 * ]
 */
class users_table {
}
```

😅

**Comment by bravoman** [comment]
I see this even works (assuming database is setup correctly in PHPStorm):
```php
/**
 * @method getById(int $id) = (new \PDO('mysql:host=localhost;db=my_db_name;', 'random', 'random'))
 *                                ->query('SELECT * FROM domain_comments LIMIT 1')
 *                                ->fetch(\PDO::FETCH_ASSOC)
 * @method getAll() = [
 *     0 => users_table::getById()
 * ]
 */
class users_table {
}
```

You're my new hero ... 🏆 😉

**Comment by klesun** [comment]
Glad you liked it.
I'll make sure references like `self::getById()` and `$this->someField` will work as well in a while.

**Comment by klesun** [comment]
Added support for `$this->` and `self::` in the doc in [2019.03.09.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/59242)
![image](https://user-images.githubusercontent.com/5202330/54071682-25387600-4268-11e9-8c84-0a47304abb4c.png)

**Comment by voku** [comment]
```@param $sale = self::createSale()``` works very good here, but "{@inheritdoc}" is not supported. Any plan to support it?

PS: thanks for this plugin, I really miss auto-completion in legacy projects :)

**Comment by klesun** [comment]
@voku, thanks for noticing, the type info from the doc is supposed to be inherited (even without the `@inheritdoc`), but apparently this does not work when you extend the class as you say, that's a bug, re-filed it in https://github.com/klesun/deep-assoc-completion/issues/85

**Comment by AustinGrey** [comment]
Thank you for an awesome plugin, I can finally document my options arrays and avoid all the mess of trying to keep track of all the options. However I'm curious how far can I take the documentation. Is it possible to document each key like I would a fully fledged parameter (specifying type and default value)? Right now I'm looking at this example:
![image](https://user-images.githubusercontent.com/20841847/59463607-a2353780-8de3-11e9-97f1-6aadc82a9540.png)
I see that the parameter 'filter_active' was suggested, but I would like to type hint that it should be an integer. It's easy enough to specify a default value like 0 which would also correctly type hint integer, but for this specific instance there is no default value, the lack of the option is the default! How can I specify the type without specifying a default?

**Comment by klesun** [comment]
@AustinGrey, maybe [psalm notation](https://github.com/klesun/deep-assoc-completion/issues/77) is what you are looking for? It's also mostly supported by the plugin:
![image](https://user-images.githubusercontent.com/5202330/59465404-5d78c300-8e1a-11e9-9d3d-b906a3b5ab77.png)
<details><summary>Click to expand code</summary>
<p>

```php
/** 
 * @param $person_id
 * @param array{
 *     filter_active: int, 
 *     filter_pokemon: int|string, 
 *     filter_min_date: string, 
 *     filter_max_date: string, 
 *     ignored_pokemon_ownership_ids: array<int>,
 * } $options 
 */
public function get_owned_pokemons($person_id, $options=[])
{
    $options[''];
}
```
</p>
</details>
The downside is that currently this format does not allow typing a comment next to a key, but I'm going to add such ability in future releases - #94

I also accidentally found out that phpstorm syntax tree parser chews such writing pretty well:
![image](https://user-images.githubusercontent.com/5202330/59466114-0247d000-8e1c-11e9-993b-5865d3dd7c65.png)
<details><summary>Click to expand code</summary>
<p>

```php
/**
 * @param $person_id
 * @param $options = [
 *     'filter_active' => (int), // if true, only active pokemon shown
 *     'filter_pokemon' => (int) ?: (string), // only shows those pokemons whose name or id appear in the array
 *     'filter_min_date' => (string),
 *     'filter_max_date' => (string),
 *     'ignored_pokemon_ownership_ids' => [(int)], // an array of pokemon_ownership_ids that will not be included
 * ]
 */
public function get_owned_pokemons($person_id, $options=[])
{
    $options[''];
}
```
</p>
</details>

**Comment by AustinGrey** [comment]
Oh man this is great! Yeah looks like psalm/phan notation would be the ideal but since there's no comments allowed yet I'll use the casting format you found second until comments come. Thanks!

**Comment by klesun** [comment]
@AustinGrey, I just added basic comments support in psalm format in [2019.06.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64014):
![image](https://user-images.githubusercontent.com/5202330/59469232-bef15f80-8e23-11e9-8ccb-5233d1d1751a.png)
```php
/**
 * @param $person_id
 * @param array{
 *     filter_active: int, // comment 1
 *     filter_pokemon: int|string,
 *     filter_min_date: string, // comment 2
 *     filter_max_date: string,
 *     ignored_pokemon_ownership_ids: array<int>, // comment 3.1
 *                                                // comment 3.2
 * } $options
 */
public function provide_psalmKeyComments($person_id, $options=[])
{
    $options[''];
    return [
        [$options, ['filter_active', 'filter_pokemon', 'filter_min_date', 'filter_max_date', 'ignored_pokemon_ownership_ids']],
    ];
}
```

**Comment by miquelbrazil** [comment]
Hey @klesun, in reference to the following:

> @AustinGrey, I just added basic comments support in psalm format in [2019.06.13.001]

Just thought I'd double check (and I may be doing something wrong) but does this newer psalm commenting support only work for the @param tag? I tried using it with the @var tag with no luck. I can definitely use the parenthetical type + comment format you discovered above if the new format doesn't work for the @var tag yet.

Dope plugin BTW.

**Comment by klesun** [comment]
Hi, @miquelbrazil.
From what I observe, `@var` does seem to work:
![image](https://user-images.githubusercontent.com/5202330/60306706-c2f7a400-9930-11e9-86e4-4bf2f5b67d14.png)
I would guess that there is a mistake somewhere in your type expression (missing coma, or `=>` instead of `:` or quotes around key names, or something...). It's also possible that some of constructs you are using are not supported by the plugin yet (like `class-of`, `key-of`, or something more trivial that I could have missed). If you post an example code, I could debug it.

I'm also opening a ticket to make parser still provide at least some completion even if it fails at some point to make it clear where you have the mistake if any - https://github.com/klesun/deep-assoc-completion/issues/99

**Comment by miquelbrazil** [comment]
Thanks for the quick reply @klesun

So a couple of things I realized in my noobish-ness with trying to get better at commenting:

1. I was attempting to make a docBlock on an array that already presented a defined structure (which is probably really silly to do)
2. I was using a @var tag over an object field when I should have been using a @property tag in a class-level docBlock.

Nonetheless, my original version looked like the following:

<img width="942" alt="Screen Shot 2019-06-27 at 7 52 30 PM" src="https://user-images.githubusercontent.com/96764/60308566-676cec80-9917-11e9-9099-2711a0c118d8.png">

You can see the parser accurately detected the current value of the element after the `=` and the possible types are present on the far right. But it doesn't have any of the comments in the auto-suggest dropdown. This is actually similar to your screenshots you've attached. The PHP Tree Parser version includes the comments after the equal sign in your screenshots and I think I mistakingly believed that the psalm notation would do the same thing. But now I'm assuming your feature addition to add comments to the psalm format was about creating readability/commenting in the docBlock while still detecting the types – not to make those comments show up in the deep-association drop down menu as well (I could be wrong though).

All that said, I reformatted the docBlock to a class-level block and changed the tag to @property. In this variation, I got the following:

<img width="944" alt="Screen Shot 2019-06-27 at 7 54 20 PM" src="https://user-images.githubusercontent.com/96764/60308746-51abf700-9918-11e9-987a-a8a1b0d8b5cf.png">

Correct current value, but no type detections and no comments. I guess it's safe to say that @property might not be a supported tag (but when I think about it, why would it need to be since you generally could define the structure of the property within the class anyway).

Which led me to my next iteration – psalm notation in the docBlock and comments following each array element:

<img width="942" alt="Screen Shot 2019-06-27 at 7 56 29 PM" src="https://user-images.githubusercontent.com/96764/60308832-a94a6280-9918-11e9-8a51-ddf56f08ee80.png">

Now we have comments but no type detection. Which still supports my previous theory about psalm notation possibly being unsupported for the @property tag.

So my final attempt was to see how well the tree parser format worked with comments on the @property tag:

<img width="944" alt="Screen Shot 2019-06-27 at 8 03 52 PM" src="https://user-images.githubusercontent.com/96764/60308866-edd5fe00-9918-11e9-89b5-18d32e259ffa.png">

Now we have current value, comments and type detection (I realize `mixed` isn't an actual type so I'm not surprised that didn't work correctly).

So I think I will go with the final format, but I figured writing all these observations up might be helpful as you work on the plugin. So sorry it's so long. A lot of this is my desire to get better at writing phpDocumentation (which is how I stumbled upon your plugin in the first place).

Thanks so much again for looking at this and being so responsive.

**Comment by klesun** [comment]
> But it doesn't have any of the comments in the auto-suggest dropdown
It's in my TODO list - https://github.com/klesun/deep-assoc-completion/issues/94#issuecomment-501889688 (will implement it this weekend I hope)

> Which still supports my previous theory about psalm notation possibly being unsupported for the @Property tag
Yeah, plugin does not support support psalm format in the `@property` yet. Filed an (anniversary) issue for that - https://github.com/klesun/deep-assoc-completion/issues/100

Thanks for the detailed explanation!

**Comment by ktomk** [comment]
Do you have a hint for hinting the return value of a function/method that is a generator / returning a Generator which generates an array (list) each is an array (list) which would map what I've read from the Psalm syntax like so:

~~~
array{0: JobType, 1: int, 2: TaskType}
~~~

so to say many of them. The exemplary code of the generator would look like:

~~~
function generator(): Generator
{
    foreach(range(1, 3) as $number) {
        yield [new JobType(), $number, new TaskType()];
    }
}
~~~

And here is the usage example:
~~~
foreach (generator() as list($job, $number, $task)) {
    $job->execute();
    $task->executed($job);
}
~~~
(simplified example, point in case is here that `$job` is being recognized of `JobType`)

I tried with `* @return Generator|[array{0: JobType, 1: int, 2: TaskType}]` and other things but didn't come to something working.

I also dropped the `Generator|` in front. Basically I don't know if it would work with `|` here at all.

Any feedback really appreciated.

**Comment by klesun** [comment]
@ktomk I have a strong feeling that what you are looking for is [templates syntax](https://psalm.dev/docs/annotating_code/templated_annotations/#builtin-templated-classes-and-interfaces):
```
 * @return Generator<array{0: JobType, 1: int, 2: TaskType}>
```

**Comment by ktomk** [comment]
Thanks for this example, it does work as well and the result looks the same: Your Phpstrom extension provides the correct hints, it's just that Phpstorm can't infer the correct type for `$job`. So probably it would also good to learn about what Phpstorm can actually parse for "typed" array return values for me to make this gap smaller.

**Comment by klesun** [comment]
@ktomk note, there is an [open issue](https://youtrack.jetbrains.com/issue/WI-30419) with `list()` in `foreach()`, it's likely related to what you are experiencing. You can upvote it - there will be 4 of us ;)

**Comment by tminich** [comment]
I've noticed that dac is doing some inference for non-array parameters as well, like in this example
![2020-01-29 094014](https://user-images.githubusercontent.com/51162280/73340732-936c9980-427b-11ea-9c3b-72a77fb5a439.jpg)

Is there a way to achieve this effect via phpdoc? Basically annotating 'this parameter should only be/ususally is one of these'.

**Comment by klesun** [comment]
@tminich, you can do it [like this](https://github.com/klesun/deep-assoc-completion/issues/50):
```php
/** @param $parameters = ['keyword1', 'keyword2', 'keyword3'][$any] */
function my_test($parameters) {}
```
![image](https://user-images.githubusercontent.com/5202330/73341493-64f3bc00-4285-11ea-991a-da824f40e0ab.png)

**Comment by tminich** [comment]
Awesome, thanks a lot

**Comment by JustACatRu** [comment]
Hello! 
Can't understand how to make this work for any numeric key of array?
It suggests only for the first (0) key:
![image](https://user-images.githubusercontent.com/12075875/126561465-f21352c8-a30d-41da-bdee-f7559e3adddb.png)
But not for any other:
![image](https://user-images.githubusercontent.com/12075875/126561490-3ad5eec5-8597-4603-b814-6a536616821f.png)
I think I'm missging something...
PS: IDE is 2020.1.1
Thanks!

**Comment by ktomk** [comment]
> It suggests only for the first (0) key [...] But not for any other

most likely b/c there is only the first (0) key in the `@var` annotation? (not reproduced as the information in the image is without text-form).

**Comment by JustACatRu** [comment]
> most likely b/c there is only the first (0) key in the `@var` annotation?

That is the question: How to make it think that there is not only first (0) key but over 9000 keys? :)

> without text-form

Sorry for that, here is the text form of this exaple:
```
/**
 * @var $employee = [[
 *                  'salary' => 800.00,
 *                  'position' => 'frontend developer',
 *                  'fullName' => 'Pupkin Vasja',
 *                  ], ...]
 */
$employee = json_decode('dummy');
$employee[1]['']
```

**Comment by ktomk** [comment]
> That is the question: How to make it think that there is not only first (0) key but over 9000 keys? :)

hard to answer honestly (for myself) as I don't know and would need to guess (never tried before)

which brings me to the idea if not already

~~~
/**   @var $employees = [
 *                  'salary' => 800.00,
 *                  'position' => 'frontend developer',
 *                  'fullName' => 'Pupkin Vasja',
 *                  ][]
 */
~~~

perhaps works? would offer the "typed" array as an array (similar to what Phpstorm allow  to annotate.

**Comment by JustACatRu** [comment]
> perhaps works?

Nope :(
![image](https://user-images.githubusercontent.com/12075875/126582773-920c2744-6f3e-49b9-a1fc-b11ebfdcaafb.png)
And even:
![image](https://user-images.githubusercontent.com/12075875/126582743-7ef5ee79-2cd0-4a12-8ac7-926ab5a55cfc.png)

**Comment by ktomk** [comment]
> Nope :(

As there weren't three guesses yet, _maybe_ a psalm type [1] ?

~~~
/**
 * @psalm-type PhoneType = array{phone: string}
 * @var $employees PhoneType[]
 */
~~~

1: https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-type

**Comment by klesun** [comment]
Hi. @JustACatRu, you probably want:
```php
/**
 * @var $employees = [
 *     $index => [
 *         'salary' => 800.00,
 *         'position' => 'frontend developer',
 *         'fullName' => 'Pupkin Vasja',
 *     ]
 * ]
 */
$employees = json_decode('dummy');
$employees[1]['']
```
![image](https://user-images.githubusercontent.com/5202330/126604707-f3d5cd6d-e083-4e20-ae50-402ef14235e4.png)
![image](https://user-images.githubusercontent.com/5202330/126604819-94b1e449-d0d8-4098-b273-2499fd6cf053.png)

**Comment by JustACatRu** [comment]
> _maybe_ a psalm type [1] ?

Neither... But thanks for trying!

> you probably want:

Yep! This one is what I want! Works like a charm. Thanks!
And, @klesun, I think this example should go strait to this page:
https://github.com/klesun/deep-assoc-completion/blob/master/docs/deep-keys-overview.md
(Yes, I looked there before asking :) with no luck...)

PS: Thank you for the great plugin!
