### ISSUE TITLE
Develop with releases

### ISSUE THREAD

**Issue by vladyslavstartsev** [klesun/deep-assoc-completion#65]
Hi! Thank you for your work! It's an awesome plugin.

Can you develop it with releases - because it asks (me) for update for every commit you make.

**Comment by klesun** [comment]
Hi.
Sorry about that, I did abuse productions for unimportant stuff few times lately.
I'll try to make it no more than one release per week from now on, unless there is a nasty bug or someone explicitly asks for some changes, will this be fine with you?

It's a bit hardcore, but you probably could also add my plugin to ignored updates list in _Appearance & Behavior -> System Settings -> Updates -> View/edit ignored updates_. It probably takes either plugin id `lv.midiana.misc.phpstorm-plugins.deep-keys` or name `deep-assoc-completion`

**Comment by vladyslavstartsev** [comment]
> will this be fine with you?

For me yes, 

Thank you!

**Comment by klesun** [comment]
Cool, I'll do my best not to spam anymore.
