### ISSUE TITLE
method suggestion for variable's method which initiate in $GLOBALS

### ISSUE THREAD

**Issue by ooghry** [klesun/deep-assoc-completion#72]
Hi
First of all Thank you for developing this plugin.
On this code,plugin should suggest `$date`'s method.
```php
<?php
function test(){
    $GLOBALS['date'] = new DateTime('now');
}
test();
//no suggestion for $date
echo $date->getTimeStamp();
```
PS:I know using  `$GLOBALS` is awful.

**Comment by ooghry** [comment]
May be same with my older issue:
https://github.com/klesun/deep-assoc-completion/issues/52

**Comment by klesun** [comment]
hope this global var type resolution won't kill your CPU =3

**Comment by klesun** [comment]
I'll be praying that this change will not cause freezes for framework users.
![image](https://user-images.githubusercontent.com/5202330/56248323-175fe700-6097-11e9-953d-fecdce2dceab.png)
I'll push the update to the main repository in a week or so.
If you want this update badly, you can download it manually from here [2019.04.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/60995)

**Comment by klesun** [comment]
sorry, needs a bit more

**Comment by klesun** [comment]
I'll be praying that this change will not cause freezes for framework users.
![image](https://user-images.githubusercontent.com/5202330/56248323-175fe700-6097-11e9-953d-fecdce2dceab.png)
![image](https://user-images.githubusercontent.com/5202330/56249519-9b1bd280-609b-11e9-9cff-fbf0bed3f88f.png)

I'll push the update to the main repository in a week or so.
If you want this update badly, you can download it manually from here [2019.04.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/60996)

**Comment by ooghry** [comment]
Thank you for your new release.the autocomplete works fine,but PHPStorm considers the variable does not exists.
Is it your plugin's job to declare the variable to phpstorm or ...?
![image](https://user-images.githubusercontent.com/200244/56380055-612b0780-6226-11e9-82be-ad57bc0b735d.png)

**Comment by klesun** [comment]
No, my plugin only deals with completion and GoTo definition. I can't contribute to the inspections for [performance reasons](https://github.com/klesun/deep-assoc-completion/issues/33#issuecomment-377044882) sadly.

The only thing I can suggest is to get rid is to uncheck "Enable inspection in global space" of "Undefined variable" inspection:
![image](https://user-images.githubusercontent.com/5202330/56392060-11a20700-6239-11e9-8511-2ed5ce4eb72c.png)
