### ISSUE TITLE
use super global ,no completion

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#74]
```php
<?php

class Request
{
    /**
     * @param string $name =$_SERVER
     * @param string $default
     *
     * @return string
     */
    public function getServer1($name, $default = '')
    {
        return $default;
    }

    /**
     * @param string $name =$_SERVER[$i]
     * @param string $default
     *
     * @return string
     */
    public function getServer2($name, $default = '')
    {
        return $default;
    }

    /**
     * @param string $name =array_keys($_SERVER)
     * @param string $default
     *
     * @return string
     */
    public function getServer3($name, $default = '')
    {
        return $default;
    }
}

$request = new Request();
$request->getServer1('!!caret!!'); //None completion
$request->getServer2('!!caret!!'); //it completes value, not key
$request->getServer3('!!caret!!'); //none completion 
```

**Comment by klesun** [comment]
Hi.
You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
```
@param string $name = array_keys($_SERVER)[$i]
```
Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.

**Comment by manaphp** [comment]
thanks for your reply, can we reference [ .phpstorm.meta.php](https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/) add a dummy function friendly?

**Comment by manaphp** [comment]
> Hi.
> You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
> 
> ```
> @param string $name = array_keys($_SERVER)[$i]
> ```
> Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.

too `not simple`, can we support same as syntax ? @param string $name = $_SERVER


> Hi.
> You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
> 
> ```
> @param string $name = array_keys($_SERVER)[$i]
> ```
> Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.

if we can configure this info in .phpstorm.xxx.php,  how beautiful! 
code  completion is just for  coding!

**Comment by manaphp** [comment]
> Hi.
> You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
> 
> ```
> @param string $name = array_keys($_SERVER)[$i]
> ```
> Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.

phpstorm has provides the completion of usperglobals

**Comment by manaphp** [comment]
> > Hi.
> > You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
> > ```
> > @param string $name = array_keys($_SERVER)[$i]
> > ```
> > Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.
> 
> too `not simple`, can we support same as syntax ? @param string $name = $_SERVER
> 
> > Hi.
> > You're almost there. If you wish to tell that `$name` is a key in `$_SERVER`, you can specify it this way:
> > ```
> > @param string $name = array_keys($_SERVER)[$i]
> > ```
> > Though currently plugin does not provide superglobals keys completion. I'll add it shortly and post a screenshot of your case with working completion.
> 
> if we can configure this info in .phpstorm.xxx.php, how beautiful!
> code completion is just for coding!


expectedArguments(\ini_get(), 0, argumentsSet("ini_values")); usage is good, but phpstorm does not support use php expression!!!!

**Comment by klesun** [comment]
> too not simple, can we support same as syntax ? @param string $name = $_SERVER

But `@param string $name = $_SERVER` would literally mean that `$name` is an array containing the keys of `$_SERVER`, not a string matching one of it's keys...

Added `$_SERVER` support in [2019.04.22.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61221) (the built-in keys suggestions would not work through php docs)
![image](https://user-images.githubusercontent.com/5202330/56493618-58715480-64f8-11e9-90d9-b0a37434ea1b.png)

**Comment by klesun** [comment]
> can we reference .phpstorm.meta.php add a dummy function friendly?

I'll research on that and will write back

**Comment by manaphp** [comment]
> > too not simple, can we support same as syntax ? @param string $name = $_SERVER
> 
> But `@param string $name = $_SERVER` would literally mean that `$name` is an array containing the keys of `$_SERVER`, not a string matching one of it's keys...
> 
> Added `$_SERVER` support in [2019.04.22.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61221) (the built-in keys suggestions would not work through php docs)
> ![image](https://user-images.githubusercontent.com/5202330/56493618-58715480-64f8-11e9-90d9-b0a37434ea1b.png)

i not update  plugin , but it can work correctly! 
![无标题](https://user-images.githubusercontent.com/16060165/56494355-8b314200-6524-11e9-9279-b5ead723ce3b.png)

**Comment by klesun** [comment]
Ok, closing this issue in favor of #75 - following .phpstorm.meta.php discussions shall continue there
