### ISSUE TITLE
centralize configure as similar as .phpstorm.meta.php of  phpstorm

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#75]
code completion is just for coding! maybe we does not want it mixed with phpdoc!

**Comment by klesun** [comment]
I guess vandalizing .phpstorm.meta.php slightly by allowing to use keyed arrays there, not just constants, sounds like a good idea =3. I'll take a look if I can by the next weekend or so...

**Comment by klesun** [comment]
Dev note: related functionality is kept in `com.jetbrains.php.lang.psi.stubs.indexes.expectedArguments.*` package.

**Comment by klesun** [comment]
Next release coming soon
![image](https://user-images.githubusercontent.com/5202330/56622259-fddf1200-6637-11e9-8b03-0bcaef1fc295.png)

**Comment by klesun** [comment]
=)
![image](https://user-images.githubusercontent.com/5202330/56623600-8dd38a80-663d-11e9-8f36-1cd8502bea44.png)

**Comment by klesun** [comment]
Released in [2019.04.24.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61313)

**Comment by manaphp** [comment]
> Released in [2019.04.24.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61313)
Wow, I'm super excited by this feature!

**Comment by manaphp** [comment]
> =)
> ![image](https://user-images.githubusercontent.com/5202330/56623600-8dd38a80-663d-11e9-8f36-1cd8502bea44.png)

if `search` method is inherited from parent class and not overwrite, it does not work!

**Comment by klesun** [comment]
Thanks for noticing - corrected that in [2019.04.24.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61330)
![image](https://user-images.githubusercontent.com/5202330/56649365-a8355480-668d-11e9-89bb-86a11146bcde.png)

**Comment by manaphp** [comment]
> Thanks for noticing - corrected that in [2019.04.24.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61330)
> ![image](https://user-images.githubusercontent.com/5202330/56649365-a8355480-668d-11e9-89bb-86a11146bcde.png)


if `Book`  not overwrite the `read`  method,it can not work.

**Comment by klesun** [comment]
hm, it does work in my setup, though:
![image](https://user-images.githubusercontent.com/5202330/56655201-a6659400-6681-11e9-98e2-4cfb9c56cbe0.png)
You sure you updated plugin to the 2019.04.24.002? Could there be a mistake in your definition perhaps?

Here is the definition that supposedly works:
    
- `Book.php`
    ```php
    <?php
    namespace Library;
    
    abstract class InfoHolder {
        public $capacity;
        public function read($params) {}
    }
    
    class Book extends InfoHolder
    {
    }
    
    (new Book())->read([
        '' => 123,
    ]);
    ```
- `.phpstorm.meta.php`
    <?php
    namespace PHPSTORM_META {
        expectedArguments(\Library\InfoHolder::read(), 0, [
            'chunkSize' => 20,
            'timeoutMs' => 20 * 1000, // 20 seconds
            'errorHandler' => function($code, $msg){},
        ]);
        expectedReturnValues(\Library\InfoHolder::read(), [
            'connection' => 0x9235256,
            'bytesChunk' => [123, 76,37, 256, 747],
            'bytesLeft' => 59198584,
        ]);
    }

**Comment by manaphp** [comment]
> hm, it does work in my setup, though, even when `Book` does not override `read()`:
> ![image](https://user-images.githubusercontent.com/5202330/56655201-a6659400-6681-11e9-98e2-4cfb9c56cbe0.png)
> You sure you updated plugin to the 2019.04.24.002 or later? Could there be a mistake in your definition perhaps?
> 
> Here is the definition that supposedly works:
> 
> * `Book.php`
>   ```
>   <?php
>   namespace Library;
>   
>   abstract class InfoHolder {
>       public $capacity;
>       public function read($params) {}
>   }
>   
>   class Book extends InfoHolder
>   {
>   }
>   
>   (new Book())->read([
>       '' => 123,
>   ]);
>   ```
> * `.phpstorm.meta.php`
>   ```
>   <?php
>   namespace PHPSTORM_META {
>       expectedArguments(\Library\InfoHolder::read(), 0, [
>           'chunkSize' => 20,
>           'timeoutMs' => 20 * 1000, // 20 seconds
>           'errorHandler' => function($code, $msg){},
>       ]);
>       expectedReturnValues(\Library\InfoHolder::read(), [
>           'connection' => 0x9235256,
>           'bytesChunk' => [123, 76,37, 256, 747],
>           'bytesLeft' => 59198584,
>       ]);
>   }
>   ```

your `\Library\InfoHolder::read()`  is not `static`.

**Comment by klesun** [comment]
And when it is static, it seems to work for me as well:
![image](https://user-images.githubusercontent.com/5202330/56731150-4c300600-6749-11e9-8ca0-16e1d76af718.png)

**Comment by klesun** [comment]
Could you post example of your code that does not work, perhaps?

**Comment by manaphp** [comment]
[app-api.zip](https://github.com/klesun/deep-assoc-completion/files/3116664/app-api.zip)

type code in app\Controllers\TimeController.php

```php
<?php

namespace App\Controllers;

use App\Models\City;
use ManaPHP\Rest\Controller;

class TimeController extends Controller
{
    public function getAcl()
    {
        return ['*' => '*'];
    }

    public function currentAction()
    {
        return City::first([],['c']); //caret
    }
}
```
not work

**Comment by klesun** [comment]
Oh, I see, your case is that you add meta info for the function that is not declared explicitly, but is inherited from `\ManaPHP\Model`:
```php
expectedArguments(\App\Models\City::first(), 1, ['city_id' => 1, 'city' => 'world', 'country_id' => 1]);
```
```php
class City extends \ManaPHP\Db\Model
{
    public $city_id;
    public $city;
    public $country_id;
    public $last_update;

    public function getDisplayField()
    {
        return 'city';
    }
}
```

**Comment by klesun** [comment]
I guess it would be useful to support such cases as well. I will look into this later.

**Comment by King2500** [comment]
Good work!

I already had such feature in mind to suggest to JetBrains :)

![image](https://user-images.githubusercontent.com/4896363/56733087-6d9bec80-675f-11e9-8981-94b03d4141ab.png)

**Comment by manaphp** [comment]
> Good work!
> 
> I already had such feature in mind to suggest to JetBrains :)
> 
> ![image](https://user-images.githubusercontent.com/4896363/56733087-6d9bec80-675f-11e9-8981-94b03d4141ab.png)

implemetion of @klesun is very user friendly.

**Comment by King2500** [comment]
@manaphp What do you mean?

**Comment by manaphp** [comment]
> @manaphp What do you mean?

i mean that  the definition of klesun completion is user friendly same as your suggest, we can provide sample data only.

**Comment by klesun** [comment]
@manaphp, I just added the support for functions that aren't declared explicily in project (like the inherited `\App\Models\City::first()` in your case) - [2019.04.27.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61505)
![image](https://user-images.githubusercontent.com/5202330/56854635-992afc80-6942-11e9-8bc5-c6e6dcdf09ed.png)

**Comment by King2500** [comment]
Added this in https://github.com/King2500/doctrine-phpstorm-meta/commit/d73e2db58ee5656c5ed20f2cff1442cf93d9fda0
(which is included in Symfony plugin)

**Comment by klesun** [comment]
I'd like to note here that even though `argumentsSet(...)` does normally work, it won't work inside another `registerArgumentsSet(...)`. To work around that, you can declare a function that returns the example value and use it where you would normally use `argumentsSet(...)`.

So instead of:
```php
registerArgumentsSet('pricingInfo', [
    'baseFare' => ['currency' => 'CAD', 'amount' => '250.00'],
    'netPrice' => ['currency' => 'USD', 'amount' => '500.00'],
]);

registerArgumentsSet('packResult', [
    'pricingInfo' => argumentsSet('pricingInfo'),
    'itinerary' => [
        ['from' => 'JFK', 'to' => 'MNL'],
        ['from' => 'MNL', 'to' => 'JFK'],
    ],
]);

expectedArguments(\Example\SomeCls::processPack(), 0, argumentsSet('packResult'));
```
![image](https://user-images.githubusercontent.com/5202330/60098474-258c4c80-9745-11e9-9fc5-12fa734feebf.png)

You can only write something like that:
```php
function describe_pricingInfo() {
    return [
        'baseFare' => ['currency' => 'CAD', 'amount' => '250.00'],
        'netPrice' => ['currency' => 'USD', 'amount' => '500.00'],
    ];
}

registerArgumentsSet('packResult', [
    'pricingInfo' => \PHPSTORM_META\describe_pricingInfo(),
    'itinerary' => [
        ['from' => 'JFK', 'to' => 'MNL'],
        ['from' => 'MNL', 'to' => 'JFK'],
    ],
]);

expectedArguments(\Example\SomeCls::processPack(), 0, argumentsSet('packResult'));
```
![image](https://user-images.githubusercontent.com/5202330/60098715-aea38380-9745-11e9-92e5-e18c591daa5f.png)

Note that `\PHPSTORM_META\` part is mandatory if your function is declared inside this namespace, even though you call it from same namespace...

You can also reference any other function/method in your project, but only with complete namespace.
