### ISSUE TITLE
Goto for array keys from .phpstorm.meta.php

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#76]
When defining array keys in `.phpstorm.meta.php` Ctrl+click produces "confusing" behavior:

It shows this popup:
![image](https://user-images.githubusercontent.com/4896363/57215492-51187380-6fed-11e9-8fc7-78c5f90995cc.png)

and i end up in dummy file called "foo.bar" (maybe because my class is named "FooBar"):
![image](https://user-images.githubusercontent.com/4896363/57215526-6ee5d880-6fed-11e9-9427-6c5d71ba5573.png)

my .phpstorm.meta.php:
![image](https://user-images.githubusercontent.com/4896363/57215470-452cb180-6fed-11e9-9155-f209ff718443.png)

I suggest to end up in the method where this array is actually coming from (`getOptions` in my case).

**Comment by klesun** [comment]
Sounds reasonable.
Done in [2019.05.06.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/61951)
![image](https://user-images.githubusercontent.com/5202330/57221623-972f0080-7008-11e9-92a6-41f17638ce24.png)

Related issue: #75

**Comment by King2500** [comment]
👍 
Wow, you have really fast release cycle :)
