### ISSUE TITLE
Support PSALM/phan phpdoc notation

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#77]
Suggested by @GDXbsv
See https://github.com/klesun/deep-assoc-completion/issues/8#issuecomment-489987560

https://github.com/vimeo/psalm/blob/master/docs/annotating_code/type_syntax/array_types.md

```php
        /** @var \Generator<array{
         *                      itemNo:string,
         *                      variants:array<array{
         *                          Code:string,
         *                          stock:array<array{
         *                                     serialNo:string,
         *                                     locationCode:string,
         *                                     differentialTaxation:bool
         *                                      }>
         *                           }>
         *                      }>
         * $products
         */
```

**Comment by klesun** [comment]
At last someone brought generics to php =-D

**Comment by klesun** [comment]
Basic support added in [2019.05.08.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/62063)

![image](https://user-images.githubusercontent.com/5202330/57371793-65e73980-719c-11e9-8755-57c5d03ea996.png)


Supported: array keys, [built-in interface](https://psalm.dev/docs/templated_annotations/#builtin-templated-classes-and-interfaces) generics
Not supported yet: scalar type values like `3.14`, `'success'`, class generics declared with `@template`

**Comment by klesun** [comment]
Added basic `@template` generic support in functions and classes - [2019.05.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/62242)
![image](https://user-images.githubusercontent.com/5202330/57588850-8cea9600-7523-11e9-918c-a3f6dc822e64.png)
![image](https://user-images.githubusercontent.com/5202330/57588894-48132f00-7524-11e9-9e24-dfb2d293a656.png)

**Comment by andrew-demb** [comment]
Nice to have add support `key-of`/`value-of` psalm types - https://github.com/vimeo/psalm/releases/tag/3.3.1

**Comment by klesun** [comment]
The `key-of`/`value-of` support feature request is moving to separate issue - https://github.com/klesun/deep-assoc-completion/issues/137. To make it clear that rest formats support described here are implemented by now.
