### ISSUE TITLE
Nice feature TODO list

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#8]
### Not Resolved Yet

Here are listed some small things that are relatively easy to implement and do not affect the whole behaviour much. Some stuff lays here for pretty long time, so if you are interested in some of these features, you can ping me, I'll start doing it. Otherwise I will implement the feature only when I need it in some of my php projects (whcih may happen... not very soon).

- Make used key completion support key chain like this: `$rcvd['rcvd']['originData']['receivedFrom']` (currentyl it only suggests the `'rcvd'` key)

- Rewrite `getBriefValueStr` so that it worked with the iterator, not array - just take first few type till string fits into the n characters.

- It would be cool to have both project-level and IDE-level settings...

- It would be nice if functions in doc comments were captured by the reference provider...

- Maybe make dependency on DB plugin optional? It would make sense if you keep useless plugins disabled to speed up startup...

- Maybe infer type of `json_decode('{"a":"5", "b": 6}')`, but with very strict depth limit and guards for >1 MiB files.

- Support GoTo method name in multi-line php doc

- Infer dynamic property assignment and `json_decode(json_encode(..., $flag))`. `BagAccess.php`:
    ```php
    private function getChain(array $keys)
    {
        $parent = $this->root;
        foreach ($keys as $key) {
            $parent = $parent->{$key} ?? null;
        }
        return $parent;
    }
    ```
- It would be pretty cool if completion worked here:
    ```php
    'JOIN '.FlightOption::TABLE.' fo ON fo.',
    ```
    IDEA does the job when there is no concatenation, but this is not always the case. So I suggest to provide the completion in any string that matches pattern `JOIN {tableName} alias ON alias.{suggestColumnsHere}`. Could go even further and actually semi-parse whole SQL string and provide completion in `WHERE`, `SELECT`, `GROUP BY`, etc... as well.

- Go To column in DB schema in the "Database" tab instead of just the `Db::exec()` expression.

- It would be nice if Reference Provider highlighted same key on same variable/field in a function.

- Used key completion should work here:
	```php
	$handler = [\Rbs\Process\Common\ImportPnr\ImportPnrAction::class, 'reportManyCmdsFromSameStoreTds'];
	$handler([
		''
	]);
	```

- ~~Infer arguments inside lambda passed to something other than `array_map` like here:~~ 50f0bf275976e21e774ae37603f0724db8e54be6
	```php
	function runUpdatePnrJobs(string $gds, callable $processPnrJob) {
		$processPnrJob(['pcc' => 'KL65', 'queue_number' => 80, 'record_locator' => 'ZXCFR2']);
	}
	runUpdatePnrJobs('apollo', function($jobRow){
		$jobRow['']; // should suggest: 'pcc', 'queue_number', 'record_locator'
	});
	```
	~~Actually I already do something similar - `ArgRes::getFuncVarUsageArg()`. Could at least make it infer type only from the direct function it is passed to to not waste performance... or put some sane depth limit.~~ Should support `array_map` and other built-in functions there. See TODO in `ArgRes::getArgFromMethodCall()`
- Provide array structure description in built-in "Show Docs" pop-up that is shown when you press _Ctrl + Q_ instead of separate (_Ctrl + Alt + Q_) shortcut. This time i should handle it, it did not work initially because of absence of "order"="first" likely. Btw, would be nice if docs were also shown when you press the shortcut inside quotes (we don't always have a var).

- Support vars in `""` string literals:
    ![image](https://user-images.githubusercontent.com/5202330/51028964-e4d0ba80-158c-11e9-8d90-f0ec92bd3211.png)

**Comment by klesun** [comment]
### Resolved

**Comment by klesun** [comment]
Marking this as closed to hide from real issues.

**Comment by klesun** [comment]
@klesun-productions

**Comment by Jurigag** [comment]
@klesun how about suggetions of keys from arrays returned by php internal functions? Like for example `debug_backtrace`

**Comment by klesun** [comment]
@Jurigag, sounds good. I'm actually already doing this for a [set of functions](https://github.com/klesun/deep-assoc-completion/blob/master/src/org/klesun/deep_assoc_completion/built_in_typedefs/ReturnTypeDefs.java) I managed to find, but apparently `debug_backtrace` wasn't among them. I'll add `debug_backtrace` to the list soon.

**Comment by klesun** [comment]
Added support for `debug_backtrace()` in [2019.04.11.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/60760)
![image](https://user-images.githubusercontent.com/5202330/55965476-2fce9c80-5c66-11e9-846a-417d24fda516.png)

**Comment by Jurigag** [comment]
Cool.

I'm also wondering if you could provide some way to define those possible keys for 3-rd party php extensions using php stubs(just empty php classes with phpdocs definiomns)? Like for example, there is c-based framework called phalcon, which just works as extension. There is method like `\Phalcon\Mvc\Model::findFirst()` which can accept array like this:

```php
$robot = Robots::findFirst(
    [
        "type = 'virtual'",
        'order' => 'name DESC',
        'limit' => 30,
    ]
);
```

Of course adding it for all extensions possible would be a a lot of effort. Maybe you could implement syntax using some kind of annotations so for example here https://github.com/phalcon/ide-stubs/blob/master/src/Phalcon/mvc/Model.php#L559 we could just add some magic thing which would your extension then use and autocomplete those names above, like order limit etc?

**Comment by klesun** [comment]
@Jurigag, if you are a contributor of `phalcon/ide-stubs`, you can specify function argument type like this:
```php
    /**
     * @param mixed $parameters = [
     *     'type' => 'virtual',
     *     'order' => 'name DESC',
     *     'limit' => 30,
     * ]
     * @return Model
     */
    public static function findFirst($parameters = null) {}
```
![image](https://user-images.githubusercontent.com/5202330/56136335-1a1ce800-5f82-11e9-8a7d-9f8f12b5aa16.png)

**Comment by Jurigag** [comment]
Oh, thanks for this.

**Comment by GDXbsv** [comment]
It would be nice to have an ability to use annotation from the PSALM static analysis. We already use it for the type analysis, so autocompleat would be the great feature in additional.

This is an example from the documentation https://psalm.dev/docs/docblock_type_syntax/#array-types

and one from me:
```
        /** @var \Generator<array{
         *                      itemNo:string,
         *                      variants:array<array{
         *                          Code:string,
         *                          stock:array<array{
         *                                     serialNo:string,
         *                                     locationCode:string,
         *                                     differentialTaxation:bool
         *                                      }>
         *                           }>
         *                      }>
         * $products
         */
```

Thanks!

**Comment by klesun** [comment]
Filed a separate issue - https://github.com/klesun/deep-assoc-completion/issues/77

**Comment by mialex** [comment]
Hello, could you tell me if it's possible to describe somehow the possibility to support a collection of assoc arrays? What I mean is the next:
```
[
    [
        'user' => [
            'id' => 123,
            'name' => 'Joe',
        ],
    ], [
        'order' => [
            'id' => 21,
            'offer_id' => 212,
        ],
    ], [
        'offer' => [
            'id' => 212,
            'name' => 'Toys',
        ],
    ],
]
```

So I could describe a possible set of options and then I can use it in any order?

**Comment by klesun** [comment]
You can also use [psalm](https://github.com/klesun/deep-assoc-completion/issues/77) format (just added support for `|` in [2019.05.29.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/63201)):
![image](https://user-images.githubusercontent.com/5202330/58520903-932a7480-81a9-11e9-8677-9c7910555f62.png)

@mialex, another trick would be to use an undefined var (for example `$any`) as key:
![image](https://user-images.githubusercontent.com/5202330/58521158-04b6f280-81ab-11e9-980e-24393dace096.png)
```
@param $records = [
    $any => ['user' => ['id' => 123, 'name' => 'Joe']],
    $any => ['order' => ['id' => 21, 'offer_id' => 212]],
    $any => ['offer' => ['id' => 212, 'name' => 'Toys']],
]
```

**Comment by Jurigag** [comment]
Im wondering if it's somehow possible - add autocomplete based on xdebug variables? @klesun

**Comment by klesun** [comment]
@Jurigag, if this is just a static set of keywords, no problem. Could you provide a link describing them?

**Comment by Jurigag** [comment]
Well i mean when xdebug session is active. Like suggest keys here:

![image](https://user-images.githubusercontent.com/10086991/63338353-eb08ef80-c342-11e9-9125-80b44c67ab2e.png)

**Comment by klesun** [comment]
https://github.com/klesun/deep-assoc-completion/issues/110
I'll look into that. If there will be a usable API I'll add it.

**Comment by Jurigag** [comment]
@klesun hey, lately i noticed pretty significat thing i would like - in unittests in phpunit there is thing called `@dataProvider` where you can provider data for tests, it would be cool if plugin could autocomplete then this data in method

**Comment by klesun** [comment]
Closing as no time for implementing the remaining minor features in the list. If someone considers some particular ones a must-have, please open a separate ticket.
