### ISSUE TITLE
array of arrays

### ISSUE THREAD

**Issue by patrickkusebauch** [klesun/deep-assoc-completion#82]
Hey,
I am not sure whether it is not supported or I just did not find it in the documentation.

Is there a way to describe an array of structured arrays? Like you have a collection of them.

**Comment by klesun** [comment]
Hi. You can use [any php expression](https://github.com/klesun/deep-assoc-completion/issues/63) if you are using the plugin format, including array of structured arrays:
```php
/**
 * @param $param = [
 *    ['field1' => 123, 'field2' => 456],
 * ]
 */
function doStuff($param) {
}
```
![image](https://user-images.githubusercontent.com/5202330/57974800-702fe180-79ad-11e9-866b-7d99c4537e68.png)

Recently it also became possible to use the [psalm linter format](https://github.com/klesun/deep-assoc-completion/issues/77), which also allows describing array of associative arrays:
```php
/**
 * @param array<array{
 *     field1: int,
 *     field2: int,
 * }> $param
 */
function doStuff($param) {
}
```
![image](https://user-images.githubusercontent.com/5202330/57974795-57273080-79ad-11e9-80f0-11daa001c3df.png)
