### ISSUE TITLE
Support for "mysqli_query" (non OOP syntax)

### ISSUE THREAD

**Issue by voku** [klesun/deep-assoc-completion#83]
Hi, can you also support "mysqli_query", etc. (the non OOP syntax) for legacy projects?

**Comment by klesun** [comment]
Added in [2019.05.23.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/62677)
![image](https://user-images.githubusercontent.com/5202330/58216349-dee2a700-7ced-11e9-8e31-7d086d5a0cc6.png)
