### ISSUE TITLE
Can you show a error if the key does not exists?

### ISSUE THREAD

**Issue by voku** [klesun/deep-assoc-completion#84]
Hi, is it possible that you can show a error / warning for missing keys? e.g. in legacy projects without good oop, there are many SQL queries without a mapping to entities, so that in the end something like ```$row['user_name']``` is used but in the select query it's called e.g. ```user.name as username``` so it's a typo and with "deep-assoc-completion" I have now auto-completion for this error but I don't see that it's wrong. I hope you understand what I mean... :)

Maybe @kalessil can help here?

**Comment by klesun** [comment]
Hi.
It would be [problematic](https://github.com/klesun/deep-assoc-completion/issues/33) to provide error highlighting the way phpstorm usually does, as resolution of just one expression with the plugin can take more than a second sometimes.
The best I could do would be to add a _Tools -> deep-completion -> Lint Current File_ button for you to either click it manually or with something like [Save Actions plugin](https://plugins.jetbrains.com/plugin/7642-save-actions).

**Comment by klesun** [comment]
Do you need such button?

**Comment by voku** [comment]
I don't think that the team would use the button, but if we can force the "Save Actions plugin" settings for everybody in the team that it could work.

**Comment by kalessil** [comment]
@voku, sorry for late response, the deep arrays inspection is currently not in our scope (a lot of efforts on my end).

**Comment by voku** [comment]
@kalessil I only thought that you maybe have a tip for this "error"-reporting thingy :)

**Comment by klesun** [comment]
Winter wrap-up, plugin is in maintenance-only mode, no big new features, sorry.

P.S. you probably know, but just in case, for wrong keys error repoprting, [PSALM](https://psalm.dev/docs/annotating_code/type_syntax/array_types/#object-like-arrays) static code analyzer works great. [Here](https://github.com/klesun/deep-assoc-completion/issues/162#issuecomment-668617400) is some relevant info for it's setup in phpstorm.

**Comment by voku** [comment]
😇 Already in use (but with phpstan) and its working very good.
