### ISSUE TITLE
phpdoc type info does not get inherited from abstract classes

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#85]
See https://github.com/klesun/deep-assoc-completion/issues/63#issuecomment-493799483

![image](https://user-images.githubusercontent.com/5202330/58020298-4e427600-7af7-11e9-996d-22f9f57e704b.png)

**Comment by klesun** [comment]
Note that type info from _interface_ methods _does get inherited_.

**Comment by klesun** [comment]
Fixed in [2019.05.20.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/62577)
![Uploading image.png…]()

**Comment by voku** [comment]
Thanks for the fix!
