### ISSUE TITLE
Allow adding free-form text comment next to each key after a `//` in psalm notation

### ISSUE THREAD

**Issue by klesun** [klesun/deep-assoc-completion#94]
Even though it's not an oficial standard (I'll check if there is already something similar in their specification).
This should work when I'm done:
```php
/**
 * @param $person_id
 * @param array{
 *     filter_active: int, // comment 1
 *     filter_pokemon: int|string,
 *     filter_min_date: string, // comment 2
 *     filter_max_date: string,
 *     ignored_pokemon_ownership_ids: array<int>, // comment 3.1
 *                                                // comment 3.2
 * } $options
 */
public function get_owned_pokemons($person_id, $options=[])
{
    $options[''];
}
```

**Comment by klesun** [comment]
Related issue - #77

**Comment by klesun** [comment]
Comments are now allowed since [2019.06.13.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64014). Will also pass them to the key type info later, as is done with normal key comments.

**Comment by klesun-misc** [comment]
ololo

**Comment by klesun-misc** [comment]
ololo

**Comment by klesun-misc** [comment]
ololo

**Comment by klesun-misc** [comment]
oko

**Comment by klesun-misc** [comment]
,nkn

**Comment by klesun** [comment]
![image](https://user-images.githubusercontent.com/5202330/60384990-db7cd100-9a8c-11e9-96c9-c8e7672c68fd.png)

Will deploy soon

**Comment by miquelbrazil** [comment]
That was fast. Is it by design to keep the double slashes in the autosuggest dropdown?

**Comment by klesun** [comment]
yeah, could not think of a better way to visually distinct them

**Comment by klesun** [comment]
Deployed in [2019.06.30.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64870)

**Comment by mylemans** [comment]
There seems to be a limit on how long the shown text comment can be (in my tests, this is 103 characters long). Can this limit be removed / extended?

**Comment by klesun** [comment]
Hm, I can make it configurable in the settings.

https://github.com/klesun/deep-assoc-completion/issues/178

Not sure when I'll have the time, but it's in my todo list now.
