### ISSUE TITLE
how to completion for returned array key

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#96]
![abc](https://user-images.githubusercontent.com/16060165/59481518-23013b80-8e97-11e9-9068-8c36031f5c21.png)

how to get completion from `rules` method by `static sample()` keys?

**Comment by manaphp** [comment]
![interface](https://user-images.githubusercontent.com/16060165/59484012-b9872a00-8ea2-11e9-8e38-008e06d8772b.png)
![admin](https://user-images.githubusercontent.com/16060165/59484013-ba1fc080-8ea2-11e9-90d0-b16845a4dad8.png)

if i add phpdoc on ` ModelInterface.php`, only, it can not work correctly, 

if also add in  Admin.php , it can work.


can we support only add in ModelInterface.php??

**Comment by klesun** [comment]
So bassically the problem is that return php doc type info does not get passed to the implementing function.
```php
interface ModelInterface
{
    /** @return array = static::sample() */
    public function rules();
}

class SomeCls
{
    public function rules($arg)
    {
        return [
            // should suggest: 'user_id', 'user_name'
            '' => 145,
        ];
    }

    public static function sample()
    {
        return [
            'user_id' => 0,
            'user_name' => '',
        ];
    }
}
```

**Comment by klesun** [comment]
Similar issue: https://github.com/klesun/deep-assoc-completion/issues/85

**Comment by klesun** [comment]
Will deploy later tonight or tomorrow.
![image](https://user-images.githubusercontent.com/5202330/59557268-dddb2780-8fc4-11e9-81fb-fab8e1accd6f.png)

**Comment by klesun** [comment]
Deployed in [2019.06.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64128)
