### ISSUE TITLE
completion words from model class properties

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#97]
![xxx](https://user-images.githubusercontent.com/16060165/59484541-c7d64580-8ea4-11e9-845c-5a62013cfb64.png)

can we support this feature?

**Comment by manaphp** [comment]
currently, the ManaPHP framework beg to `Model::sample()` method  technically, 


if we support this feature, `ManaPHP` framework can remove ugly `sample()` method!

**Comment by klesun** [comment]
So, do I get it right, what you want is an ability to specify in php doc that returned value is an associative array containing keys matching the class fields?
Will such format satisfy you?
```php
class SomeCls
{
    public $prop1 = 5;
    public $prop2 = 6;
    public $prop3 = ['a' => 5, 'vb' => 7];

    /** @return array = get_object_vars($this) */
    public static function rules($arg)
    {
        return [
            // should suggest: 'prop1', 'prop2', 'prop3'
            '' => 145,
        ];
    }
}
```

**Comment by manaphp** [comment]
YES, YES!!!!

very good!!!!!

**Comment by klesun** [comment]
will deploy later today or tommorow
![image](https://user-images.githubusercontent.com/5202330/59557190-49bc9080-8fc3-11e9-9d22-e7df39881eee.png)
<details><summary>Click To Expand Code</summary>

```php
abstract class Model
{
    /** @return array = get_object_vars(new static) */
    abstract static public function rules();
}

class Admin extends Model
{
    public $admin_id;
    public $admin_name;
    public $status;

    public static function rules()
    {
        return [
            '' => 123,
        ];
    }
}
```
</details>

**Comment by klesun** [comment]
Deployed in [2019.06.16.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64128)

**Comment by manaphp** [comment]
i have test it , it works,


but i found a little question, it complete protected properties, 

 to support `get_class_vars(static::class)`?

![QQ截图20190616214149](https://user-images.githubusercontent.com/16060165/59565577-15f76e80-9088-11e9-83c8-ab66973015d9.png)

**Comment by klesun** [comment]
[get_object_vars()](https://php.net/manual/en/function.get-object-vars.php)

> Gets the accessible non-static properties of the given object according to scope

If you are using it as `get_object_vars($this)` or `get_object_vars(new static)` I think it makes sense that it includes protected properties, as they would be returned in the real code.

I will add `get_class_vars` support later, but if I get it right, it won't solve your protected property problem.

**Comment by manaphp** [comment]
> 
> 
> [get_object_vars()](https://php.net/manual/en/function.get-object-vars.php)
> 
> > Gets the accessible non-static properties of the given object according to scope
> 
> If you are using it as `get_object_vars($this)` or `get_object_vars(new static)` I think it makes sense that it includes protected properties, as they would be returned in the real code.
> 
> I will add `get_class_vars` support later, but if I get it right, it won't solve your protected property problem.

if the call is not inside the method,  protected is not accessible,  it is a bug?


```php
//deep-assoc-completion\src\org\klesun\deep_assoc_completion\resolvers\FieldRes.java

    /**
     * includes both dynamic props and props belonging to class
     * not sure, but probably should use this in resolve() to remove duplicating code
     */
    public static It<DeepType.Key> getPublicProps(Mt mt, Project proj, IExprCtx memCtx)
```

**Comment by manaphp** [comment]
```php
    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param int|string|array $filters =get_object_vars(new static)
     * @param array            $fields =get_object_vars(new static)
     *
     * @return static|null
     */
    public static function first($filters, $fields = null);

/**
     * @param array $fields =get_object_vars(new static)
     *
     * @return array
     */
    public function except($fields)
```

```php
  City::first(['x'])// ok
  City::get(1)->except(['']);// none completions
```

it not work, if use `get_object_vars(new static)` on non-static method?

**Comment by klesun** [comment]
> it does't work, if using get_object_vars(new static) on non-static method?

Thanks for the great test case. Yeah, it did not infer the final class because plugin only used static method call context for the resolution. Will be fixed in the monday release.
![image](https://user-images.githubusercontent.com/5202330/60387468-573a4600-9aac-11e9-99bf-ebe971a77655.png)

**Comment by klesun** [comment]
(or a sunday release...)
Deployed in [2019.06.30.001](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/64870)
